#!/usr/bin/env python3
"""Build dist/collect.sh, the single file an MDM deploys, around the vendored bundler.

    tools/build-collector.py            write dist/collect.sh
    tools/build-collector.py --check    fail if it does not carry the vendored tree

THE SELF-EXTRACTING HALF IS UPSTREAM'S NOW, AND IT USED TO BE HERE. This file carried its
own reproducible tar, its own base64/gzip wrapping and its own extraction preamble -- mktemp,
`base64 -D` with a `-d` fallback, tar, chmod -- and from v0.6.0 upstream ships exactly that as
tools/bundle.py, tested on its macOS AND Linux runners. Two copies of one mechanism is the
failure this repo is organised around; the local one is gone.

WHAT IS STILL OURS IS THE DRIVER, and it is the whole of what made the old file Arthur's:
/var/lib/arthur, the 15s cold-Docker ping bound, the keep-the-last-good-scan policy, the
`arthur1.` frame, the 256 KB cap and its ERROR:oversize reason, and the Jamf status line. None
of those is a fact about osquery, which is why upstream deleted `--framed` and offers a
--driver hook instead of a place to put them.

SO THE SEAM NOW READS: upstream packs bin/ and dist/ into one self-extracting script and runs
what it is given; this repo writes what it is given. `AI_DISCOVERY_ROOT` is the interface --
the wrapper sets it to the extracted tree and runs the driver with it.

ONE THING GOT WORSE AND IT IS WORTH KNOWING. The macOS-only refusal is upstream's message now,
and it ends "Build the other one with tools/bundle.py --platform" -- a sentence about a tool a
Jamf admin does not have. It still names the real cause (this bundle carries the darwin
artifact), it fires before anything is unpacked, and the alternative is a second platform
guard here, which is the duplication this change exists to remove.

NO CATALOG IN THE PAYLOAD. Upstream refuses it too, but only in its own main(); this builds
through bundle.build() and so asserts it here. The endpoint enumerates and matches nothing --
see docs/architecture.md.
"""

import importlib.util
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDOR = ROOT / "vendor" / "osquery-ai-discovery"
DIST = ROOT / "dist"
OUT = DIST / "collect.sh"
PLATFORM = "darwin"


def vendored_bundler():
    """Import tools/bundle.py out of the vendored tree.

    By path, not by name: the vendored tools/ is not a package and must not become one --
    an __init__.py here would be an edit to a vendored tree, which tools/vendor-queries.sh
    overwrites wholesale on the next bump.
    """
    path = VENDOR / "tools" / "bundle.py"
    if not path.is_file():
        sys.exit(
            f"no {path.relative_to(ROOT)} -- the collector is built by upstream's "
            f"bundler. Re-vendor at v0.6.0 or later with tools/vendor-queries.sh.",
        )
    # Importing writes __pycache__ beside the module, which would have the build editing
    # vendor/ -- the one directory this tree does not edit. Restored rather than left set,
    # because a caller may have imported this module for one function.
    was = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec = importlib.util.spec_from_file_location("vendored_bundle", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
    finally:
        sys.dont_write_bytecode = was
    return mod


# DARWIN ONLY, AND NAMED. Upstream ships a Linux artifact and a Linux bundle; what this repo
# deploys is a macOS collector -- a LaunchDaemon and Jamf Extension Attributes -- so it builds
# the darwin one and says so. Embedding the Linux half would ship a platform claim nothing
# here tests.
DRIVER = r"""#!/bin/bash
# GENERATED by tools/build-collector.py. Do not edit; rebuild.
#
# The Arthur half of the collector: what to do with the tree the bundle just extracted.
# Upstream's wrapper sets AI_DISCOVERY_ROOT to it and runs this. Everything here is a
# property of Arthur's reporting channel rather than of osquery -- which is exactly why it
# lives on this side of the seam.
#
#   $OUT/inventory.json   the readable payload
#   $OUT/inventory.ea     the framed value to report, ~21KB of a 256KB budget
#   $OUT/status.txt       one line, for a Smart Group to match on
#
# WHY A SCHEDULED SCRIPT AND NOT AN EXTENSION ATTRIBUTE. osquery's docker_images has no
# timeout of its own, and against a daemon that answers /_ping and then stops serving, the
# query does not return. No documented Jamf timeout for an EA script exists, so an unbounded
# EA does not fail fast -- it hangs that Mac's inventory collection. Nothing waits on a Policy.
set -uo pipefail

# Set by the bundle's wrapper, which extracted bin/ and dist/ into a private temp directory
# and removes it on the way out. Guarded rather than assumed: run by hand without the wrapper
# this would otherwise fail somewhere further down, as a missing path.
[ -n "${AI_DISCOVERY_ROOT:-}" ] || {
  echo "arthur: AI_DISCOVERY_ROOT is not set. This is the driver half of dist/collect.sh;" \
       "run that, not this." >&2; exit 1; }

OUT="${ARTHUR_OUT_DIR:-/var/lib/arthur}"

mkdir -p "$OUT" 2>/dev/null || { echo "arthur: cannot create $OUT" >&2; exit 1; }

# THE PING TIMEOUT IS 15s, ABOVE UPSTREAM'S DEFAULT OF 8. Why a cold daemon needs a longer
# ping, and what each Docker state costs, is upstream's docs/containers.md. What is this
# repo's is the number: 15 clears the ~10s a wedged engine takes to answer 500, so the branch
# reports `unhealthy:500` instead of collapsing it into an indistinguishable `000`. Upstream
# sizes its default against a 10s budget that does not bind here -- this runs in the scheduled
# collector, not the Extension Attribute, whose side is a `cat`. test/lint.sh holds the floor.
#
# The cost lands off the reporting path: no socket means no ping at all (`absent`,
# immediately), so this only spends time where a socket exists but nothing answers.
# Overridable, because a fleet that has measured its own Macs should use its own number.
export DOCKER_PING_TIMEOUT="${DOCKER_PING_TIMEOUT:-15}"

# Writes by rename, so a reader catching this mid-run sees the previous complete file rather
# than a truncated one.
# A FAILED SCAN MUST NOT REPLACE A GOOD ONE, IN EITHER DIRECTION. discover's exit status used
# to be discarded -- no `set -e`, no `||` -- and because discover writes by rename, a failed
# run left the previous inventory.json in place and the framing step below re-framed it into a
# fresh-looking value and exited 0. Measured: a Mac that lost osquery reported `ok` with a
# stale timestamp and a green policy, having collected nothing.
#
# The fix is NOT to delete the last good scan. On an Ongoing schedule a transient failure is
# ordinary, and discarding a good payload because one run could not look would report a
# well-equipped Mac as empty -- the same wrong answer in the other direction, and the one this
# project treats as its most dangerous. So: keep the last successful scan, serve it, and fail
# the POLICY rather than the data. Jamf then carries the best evidence this Mac ever produced
# while its policy log says plainly that the latest attempt did not run.
#
# HOW A READER TELLS IT IS OLD. The kept payload dates itself -- the status line opens with a
# UTC timestamp and every branch carries a dated kind=scan row -- so age is a property of the
# value, not of the file's mtime, which a redeploy would reset. Nothing here is silently
# refreshed: on this path no file is rewritten at all.
#
# SAFE TO TREAT NON-ZERO AS FATAL, which is worth checking rather than assuming: every failure
# path in discover's --write branch leaves the destination alone and says so ("produced no
# payload; $WRITE left alone"). A branch that could not look is NOT a failure -- it writes a
# dated kind=scan row, the status line says `degraded`, exit 0. So non-zero always means
# nothing was written, never that good rows are being kept in place of better ones.
"$AI_DISCOVERY_ROOT/bin/discover" \
  --write  "$OUT/inventory.json" \
  --status "$OUT/status.txt" > /dev/null || {
  echo "arthur: discover failed. Is osquery installed?" >&2
  if [ -s "$OUT/inventory.ea" ] && [ -s "$OUT/status.txt" ]; then
    # Keep and serve what the last successful run produced. Its own timestamp says how old it
    # is; this run adds nothing and removes nothing.
    echo "arthur: keeping the last successful scan; the value below is that run, not this one" >&2
    cat "$OUT/status.txt"
    exit 1
  fi
  # Nothing good was ever written here, so there is nothing to keep and no value to serve.
  # Leave no partial file behind claiming to be a result: both attributes report `no-cache`,
  # which is true and is what the "not reporting" Smart Group finds.
  rm -f "$OUT/inventory.json" "$OUT/status.txt" "$OUT/inventory.ea"
  echo "arthur: no previous scan to fall back on; no attribute value written" >&2
  exit 1
}

# THE FRAMED VALUE IS BUILT HERE, not by bin/discover: `arthur1.` is Arthur's wire format and
# the size budget a property of the reporting channel, and neither is a fact about osquery.
#
# The writer frames rather than the reader because the raw JSON is ~127 KB on a reference Mac
# against ~21 KB framed, so the reporting path cannot carry the raw file. Framing here keeps
# that path a literal `cat`, and needs no interpreter on either side.
#
# BY RENAME, for the same reason as the payload above: a reader catching a half-written value
# uploads a truncated base64 blob, which decodes to nothing at all.
#
# OVER THE CAP WRITES A REASON, NOT NOTHING. An absent, empty or stale attribute value is
# indistinguishable from a Mac with no AI tools on it -- this project's most dangerous failure
# mode -- so an oversize payload replaces the value with ERROR:oversize:<bytes>, unframed and
# matchable by a Smart Group. This is the only implementation of that rule left: an inline
# Extension Attribute script in this repo carried a second one, and it is gone.
# FRAMED WITH BASE macOS TOOLS ONLY -- gzip, base64 and plutil, each in /usr/bin on a stock
# install. This was `python3 -c` until it was measured against a real fleet, and python3 is NOT
# part of macOS: /usr/bin/python3 is a shim for whatever the active developer directory
# provides, so on a Mac without Command Line Tools it fails and the collector wrote nothing.
# That surfaced as `no-cache` -- the same value a Mac with no AI tools reports -- so the
# fleet's largest blind spot looked like a clean result. Deleting the interpreter deletes the
# prerequisite; the reading path was already a `cat`, and now the writing path is base macOS.
#
# THE MINIFY STEP WENT WITH IT AND COST NOTHING. bin/discover already writes compact JSON --
# verified byte-identical to json.dumps(separators=(",",":")), 126,741 bytes on a reference
# Mac -- so the round trip was re-serialising a file already in its final form.
#
# VALIDATED ANYWAY, because json.load() was buying one real thing: a corrupt or truncated
# payload refused rather than published. plutil -convert parses the JSON and exits non-zero on
# a bad file. `plutil -lint` does NOT work here -- it reads the file as a property list and
# rejects a top-level array whether or not the JSON is valid, which makes it no discriminator.
plutil -convert binary1 -o /dev/null "$OUT/inventory.json" 2>/dev/null || {
  rm -f "$OUT/inventory.ea"
  echo "arthur: inventory.json is not parseable JSON; no attribute value written" >&2
  exit 1
}

# ONE LINE, WHATEVER base64 DOES. Line wrapping differs between base64 implementations and
# versions; `tr -d` makes the result one line regardless, and the attribute must be one line --
# the EA reader wraps `cat` output in <result> and a wrapped value would carry newlines into it.
eatmp="$OUT/inventory.ea.$$"
{ printf 'arthur1.'; gzip -9 -c "$OUT/inventory.json" | base64 | tr -d '\n'; } > "$eatmp" || {
  # No framed value at all is the one framing outcome that cannot report itself. Leave no
  # stale file behind claiming to be current, and fail loudly: the attribute is the
  # deliverable, and a reader cannot tell an old value from a new one.
  rm -f "$eatmp" "$OUT/inventory.ea"
  echo "arthur: could not frame the payload; no attribute value written" >&2
  exit 1
}

# 256 KB, and it is NOT a platform limit. Measured 2026-09-05: a 1,048,576-byte Extension
# Attribute survived script -> `jamf recon` -> API read with an identical sha256. Jamf
# documents no value cap and the column is LONGTEXT.
#
# The budget is not about bandwidth -- fleet cost is payload x fleet whatever this number says
# -- it is about WHOSE FAILURE FIRES FIRST. Ours is loud and known: ERROR:oversize:<bytes>,
# naming the fault and its size. Past Jamf's own limit the behaviour is unobserved: 1 MB was
# measured as a floor, never a ceiling, and it might truncate, drop the attribute, or refuse
# the whole submission and cost that Mac its recon.
#
# At the measured 25.4 framed bytes per row the cap fires near 10,300 rows, against the ~840 a
# loaded developer Mac carries. A Mac at 10,000 rows is a defect rather than a heavy Mac, so
# this doubles as a tripwire for a runaway branch.
CAP=262144
bytes=$(wc -c < "$eatmp" | tr -d ' ')
if [ "$bytes" -gt "$CAP" ]; then
  echo "arthur: framed value is $bytes bytes, over the $CAP-byte cap by $((bytes - CAP)). Reporting the reason instead of the payload." >&2
  printf 'ERROR:oversize:%s' "$bytes" > "$eatmp"
else
  echo "arthur: framed $(wc -c < "$OUT/inventory.json" | tr -d ' ') bytes of JSON into $bytes bytes ($(( (bytes * 100 + CAP / 2) / CAP ))% of cap)" >&2
fi

# BY RENAME, and 644 so the EA script can read it as any user.
printf '\n' >> "$eatmp"
chmod 644 "$eatmp"
mv -f "$eatmp" "$OUT/inventory.ea" || {
  rm -f "$eatmp" "$OUT/inventory.ea"
  echo "arthur: could not publish the attribute value" >&2
  exit 1
}

# Jamf records a script's exit status and shows a non-zero one as a failed Policy. A branch
# that could not look is NOT a failed collection -- the payload says so per branch, and the
# status file is what a Smart Group reads. Only an actual inability to collect is an error.
[ -s "$OUT/status.txt" ] || { echo "arthur: no status written" >&2; exit 1; }
cat "$OUT/status.txt"
exit 0
"""


def collector(bundle, label):
    """dist/collect.sh: upstream's wrapper around the vendored tree, running our driver."""
    # The driver reaches the bundler as a FILE because that is its interface -- it goes into
    # the payload tar like any other member, with its mtime, uid and mode pinned there. Which
    # temporary path it had does not reach the artifact: the member is named `driver`.
    with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as fh:
        fh.write(DRIVER)
        tmp = fh.name
    try:
        return bundle.build(VENDOR, PLATFORM, driver=tmp, label=label), tmp
    finally:
        pass


def driver_of(bundle, path):
    """The driver as it actually SHIPS, read back out of a built collector.

    EVERY GUARD THAT USED TO GREP dist/collect.sh NEEDS THIS. The Arthur half is inside the
    payload now -- base64 of gzip of a tar -- so `grep arthur1.` on the artifact finds
    nothing, and a guard that finds nothing either fails for the wrong reason or passes
    vacuously. Both are worse than the text scan they replaced. Reading the member back is
    the version of that check which asserts on what a Mac will run, which is the standing
    rule here: measure what actually ships.

    THROUGH THE SUPPORTED READER, AND IT WAS NOT ONE WHEN THIS WAS WRITTEN. The first
    version unpacked the payload here, through the underscore-prefixed splitter, then gzip,
    then tarfile -- a downstream repo pinned to a private function. That is the exact shape
    of the breakage this project has already taken once: upstream removed
    `bin/discover --framed`, correctly, and it took this collector with it. Upstream added
    read_member() at v0.7.0 for this reason. A private call that works is still a private
    call, and the point of asking for the interface was not to be allowed to keep one.
    """
    try:
        return bundle.read_member(pathlib.Path(path).read_text(), "driver").decode()
    except KeyError:
        sys.exit(
            f"{path} carries no driver -- it was not built by tools/build-collector.py.",
        )
    except bundle.CorruptBundle as exc:
        sys.exit(f"{path} is not a readable bundle: {exc}")
    except ValueError:
        # NOT A BUNDLE AT ALL, AND FIXED UPSTREAM AT v0.7.1, which raises CorruptBundle for
        # this like everything else -- so at the vendored ref the branch above catches it
        # and this one does not fire. It stays because tools/vendor-queries.sh accepts any
        # ref from v0.6.0, and at v0.6.0 and v0.7.0 a file with no payload marker comes
        # back as a bare ValueError from str.index. A consumer should not read a traceback
        # to learn it named the wrong file, whichever ref it happens to be pinned at.
        sys.exit(f"{path} carries no payload marker -- it is not a bundle.")


def vendored_ref():
    """The pinned ref, which rides along in the bundle's banner."""
    version = (VENDOR / "VERSION").read_text().splitlines()
    return next(
        (l.split(None, 1)[1].strip() for l in version if l.startswith("ref")),
        "?",
    )


def main():
    check = "--check" in sys.argv
    if "--driver-of" in sys.argv:
        # For the guards in test/, so there is ONE implementation of unpacking a collector
        # rather than one in lint.sh and another in run-collector.sh.
        target = sys.argv[sys.argv.index("--driver-of") + 1]
        sys.stdout.write(driver_of(vendored_bundler(), target))
        return
    if not VENDOR.exists():
        sys.exit(
            "no vendor/osquery-ai-discovery/ -- run tools/vendor-queries.sh <ref> first",
        )
    bundle = vendored_bundler()

    # A MISSING PAYLOAD FILE IS MORE OFTEN A RENAME THAN A BAD VENDOR RUN. v0.3.0 replaced
    # dist/discovery.sql with per-platform files and this check is what caught it. The list
    # itself is upstream's now -- one less copy to drift -- but the failure it produces is
    # still ours to explain.
    files = bundle.payload_files(PLATFORM)
    missing = [f for f in files if not (VENDOR / f).is_file()]
    if missing:
        sys.exit(
            f"vendored tree does not carry {missing}. Either the vendor run was "
            f"incomplete, or upstream renamed or dropped it in this ref -- check the "
            f"release notes. Re-vendoring will not fix a rename.",
        )

    # The catalog must NOT be in the payload. Upstream asserts this in its own main(), which
    # this does not go through, and the failure -- a Mac carrying the signatures it is
    # supposed to enumerate past -- would be invisible in a 25KB base64 blob.
    if any("catalog" in f or f.endswith(("agents.yaml", "routes.yaml")) for f in files):
        sys.exit(
            "the vendored bundler would pack the catalog. The endpoint holds no catalog.",
        )

    label = vendored_ref()
    built, tmp = collector(bundle, label)
    try:
        if check:
            if not OUT.exists():
                sys.exit(
                    f"{OUT.relative_to(ROOT)} is missing. Run tools/build-collector.py.",
                )
            # COMPARED BY MEANING, NOT BY BYTES -- upstream's matches() decompresses the
            # payload and compares the tar, because zlib's output is not identical across
            # zlib versions and a byte comparison fails at random on a CI runner against
            # content that matches. That lesson was learned here and went upstream with the
            # code.
            if not bundle.matches(
                OUT.read_text(),
                VENDOR,
                PLATFORM,
                driver=tmp,
                label=label,
            ):
                sys.exit(
                    f"{OUT.relative_to(ROOT)} does not carry the vendored tree or the "
                    f"current driver. Run tools/build-collector.py.",
                )
            print(f"{OUT.relative_to(ROOT)} is up to date (vendored ref {label})")
            return
        DIST.mkdir(exist_ok=True)
        OUT.write_text(built)
        OUT.chmod(0o755)
        print(
            f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB, "
            f"{len(files)} vendored files + the Arthur driver, ref {label})",
        )
    finally:
        pathlib.Path(tmp).unlink(missing_ok=True)


if __name__ == "__main__":
    main()
