# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.llm_config_settings import LLMConfigSettings
from arthur_genai_client.models.llm_tool_output import LLMToolOutput
from arthur_genai_client.models.model_provider import ModelProvider
from arthur_genai_client.models.open_ai_message_output import OpenAIMessageOutput
from typing import Optional, Set
from typing_extensions import Self

class AgenticPrompt(BaseModel):
    """
    AgenticPrompt
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the agentic prompt")
    messages: List[OpenAIMessageOutput] = Field(description="List of chat messages in OpenAI format (e.g., [{'role': 'user', 'content': 'Hello'}])")
    model_name: StrictStr = Field(description="Name of the LLM model (e.g., 'gpt-4o', 'claude-3-sonnet')")
    model_provider: ModelProvider = Field(description="Provider of the LLM model (e.g., 'openai', 'anthropic', 'azure')")
    version: Optional[StrictInt] = Field(default=1, description="Version of the agentic prompt")
    tools: Optional[List[LLMToolOutput]] = None
    variables: Optional[List[StrictStr]] = Field(default=None, description="List of variable names for the agentic prompt")
    tags: Optional[List[StrictStr]] = Field(default=None, description="List of tags for this agentic prompt version")
    config: Optional[LLMConfigSettings] = None
    created_at: datetime = Field(description="Timestamp when the prompt was created.")
    deleted_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["name", "messages", "model_name", "model_provider", "version", "tools", "variables", "tags", "config", "created_at", "deleted_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgenticPrompt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # set to None if tools (nullable) is None
        # and model_fields_set contains the field
        if self.tools is None and "tools" in self.model_fields_set:
            _dict['tools'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgenticPrompt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "messages": [OpenAIMessageOutput.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "model_name": obj.get("model_name"),
            "model_provider": obj.get("model_provider"),
            "version": obj.get("version") if obj.get("version") is not None else 1,
            "tools": [LLMToolOutput.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None,
            "variables": obj.get("variables"),
            "tags": obj.get("tags"),
            "config": LLMConfigSettings.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "created_at": obj.get("created_at"),
            "deleted_at": obj.get("deleted_at")
        })
        return _obj


