# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, SecretStr, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from arthur_genai_client.models.rag_api_key_authentication_provider_enum import RagAPIKeyAuthenticationProviderEnum
from typing import Optional, Set
from typing_extensions import Self

class ApiKeyRagAuthenticationConfigRequest(BaseModel):
    """
    ApiKeyRagAuthenticationConfigRequest
    """ # noqa: E501
    authentication_method: Optional[StrictStr] = 'api_key'
    api_key: SecretStr = Field(description="API key to use for authentication.")
    host_url: Annotated[str, Field(min_length=1, strict=True)] = Field(description="URL of host instance to authenticate with.")
    rag_provider: RagAPIKeyAuthenticationProviderEnum = Field(description="Name of RAG provider to authenticate with.")
    __properties: ClassVar[List[str]] = ["authentication_method", "api_key", "host_url", "rag_provider"]

    @field_validator('authentication_method')
    def authentication_method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['api_key']):
            raise ValueError("must be one of enum values ('api_key')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiKeyRagAuthenticationConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiKeyRagAuthenticationConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authentication_method": obj.get("authentication_method") if obj.get("authentication_method") is not None else 'api_key',
            "api_key": obj.get("api_key"),
            "host_url": obj.get("host_url"),
            "rag_provider": obj.get("rag_provider")
        })
        return _obj


