# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.chat_document_context import ChatDocumentContext
from arthur_genai_client.models.external_rule_result import ExternalRuleResult
from typing import Optional, Set
from typing_extensions import Self

class ChatResponse(BaseModel):
    """
    ChatResponse
    """ # noqa: E501
    inference_id: StrictStr = Field(description="ID of the inference sent to the chat")
    conversation_id: StrictStr = Field(description="ID of the conversation session")
    timestamp: StrictInt = Field(description="Time the inference was made in unix milliseconds")
    retrieved_context: List[ChatDocumentContext] = Field(description="related sections of documents that were most relevant to the inference prompt. Formatted as a list of retrieved context chunks which include document name, seq num, and context.")
    llm_response: StrictStr = Field(description="response from the LLM for the original user prompt")
    prompt_results: List[ExternalRuleResult] = Field(description="list of rule results for the user prompt")
    response_results: List[ExternalRuleResult] = Field(description="list of rule results for the llm response")
    model_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["inference_id", "conversation_id", "timestamp", "retrieved_context", "llm_response", "prompt_results", "response_results", "model_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChatResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in retrieved_context (list)
        _items = []
        if self.retrieved_context:
            for _item_retrieved_context in self.retrieved_context:
                if _item_retrieved_context:
                    _items.append(_item_retrieved_context.to_dict())
            _dict['retrieved_context'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in prompt_results (list)
        _items = []
        if self.prompt_results:
            for _item_prompt_results in self.prompt_results:
                if _item_prompt_results:
                    _items.append(_item_prompt_results.to_dict())
            _dict['prompt_results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in response_results (list)
        _items = []
        if self.response_results:
            for _item_response_results in self.response_results:
                if _item_response_results:
                    _items.append(_item_response_results.to_dict())
            _dict['response_results'] = _items
        # set to None if model_name (nullable) is None
        # and model_fields_set contains the field
        if self.model_name is None and "model_name" in self.model_fields_set:
            _dict['model_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChatResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inference_id": obj.get("inference_id"),
            "conversation_id": obj.get("conversation_id"),
            "timestamp": obj.get("timestamp"),
            "retrieved_context": [ChatDocumentContext.from_dict(_item) for _item in obj["retrieved_context"]] if obj.get("retrieved_context") is not None else None,
            "llm_response": obj.get("llm_response"),
            "prompt_results": [ExternalRuleResult.from_dict(_item) for _item in obj["prompt_results"]] if obj.get("prompt_results") is not None else None,
            "response_results": [ExternalRuleResult.from_dict(_item) for _item in obj["response_results"]] if obj.get("response_results") is not None else None,
            "model_name": obj.get("model_name")
        })
        return _obj


