# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreationSource(BaseModel):
    """
    Source information for how an unregistered agent was created.  .. deprecated::     This flat CreationSource model is deprecated.     Use the discriminated union CreationSource from     arthur_common.models.agent_governance_schemas instead.
    """ # noqa: E501
    task_id: Optional[StrictStr] = None
    top_level_span_name: Optional[StrictStr] = None
    gcp_project_id: Optional[StrictStr] = None
    gcp_region: Optional[StrictStr] = None
    gcp_reasoning_engine_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["task_id", "top_level_span_name", "gcp_project_id", "gcp_region", "gcp_reasoning_engine_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreationSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if top_level_span_name (nullable) is None
        # and model_fields_set contains the field
        if self.top_level_span_name is None and "top_level_span_name" in self.model_fields_set:
            _dict['top_level_span_name'] = None

        # set to None if gcp_project_id (nullable) is None
        # and model_fields_set contains the field
        if self.gcp_project_id is None and "gcp_project_id" in self.model_fields_set:
            _dict['gcp_project_id'] = None

        # set to None if gcp_region (nullable) is None
        # and model_fields_set contains the field
        if self.gcp_region is None and "gcp_region" in self.model_fields_set:
            _dict['gcp_region'] = None

        # set to None if gcp_reasoning_engine_id (nullable) is None
        # and model_fields_set contains the field
        if self.gcp_reasoning_engine_id is None and "gcp_reasoning_engine_id" in self.model_fields_set:
            _dict['gcp_reasoning_engine_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreationSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_id": obj.get("task_id"),
            "top_level_span_name": obj.get("top_level_span_name"),
            "gcp_project_id": obj.get("gcp_project_id"),
            "gcp_region": obj.get("gcp_region"),
            "gcp_reasoning_engine_id": obj.get("gcp_reasoning_engine_id")
        })
        return _obj


