# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.agent_creation_source import AgentCreationSource
from arthur_genai_client.models.data_source import DataSource
from arthur_genai_client.models.llm_model import LLMModel
from arthur_genai_client.models.rule_response import RuleResponse
from arthur_genai_client.models.sub_agent import SubAgent
from arthur_genai_client.models.tool import Tool
from typing import Optional, Set
from typing_extensions import Self

class EnrichedTaskResponse(BaseModel):
    """
    Response model for agent-tasks endpoint with enriched metadata.
    """ # noqa: E501
    id: StrictStr = Field(description="Task ID")
    name: StrictStr = Field(description="Task name")
    created_at: datetime = Field(description="Task creation timestamp")
    updated_at: datetime = Field(description="Task last update timestamp")
    is_autocreated: Optional[StrictBool] = Field(default=False, description="Whether this task was auto-created (vs manually created)")
    creation_source: Optional[AgentCreationSource] = None
    last_fetched: Optional[datetime] = None
    tools: Optional[List[Tool]] = None
    sub_agents: Optional[List[SubAgent]] = None
    models: Optional[List[LLMModel]] = None
    data_sources: Optional[List[DataSource]] = None
    num_spans: Optional[StrictInt] = None
    rules: Optional[List[RuleResponse]] = Field(default=None, description="Rules associated with this task")
    __properties: ClassVar[List[str]] = ["id", "name", "created_at", "updated_at", "is_autocreated", "creation_source", "last_fetched", "tools", "sub_agents", "models", "data_sources", "num_spans", "rules"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrichedTaskResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creation_source
        if self.creation_source:
            _dict['creation_source'] = self.creation_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_agents (list)
        _items = []
        if self.sub_agents:
            for _item_sub_agents in self.sub_agents:
                if _item_sub_agents:
                    _items.append(_item_sub_agents.to_dict())
            _dict['sub_agents'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in data_sources (list)
        _items = []
        if self.data_sources:
            for _item_data_sources in self.data_sources:
                if _item_data_sources:
                    _items.append(_item_data_sources.to_dict())
            _dict['data_sources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict['rules'] = _items
        # set to None if creation_source (nullable) is None
        # and model_fields_set contains the field
        if self.creation_source is None and "creation_source" in self.model_fields_set:
            _dict['creation_source'] = None

        # set to None if last_fetched (nullable) is None
        # and model_fields_set contains the field
        if self.last_fetched is None and "last_fetched" in self.model_fields_set:
            _dict['last_fetched'] = None

        # set to None if tools (nullable) is None
        # and model_fields_set contains the field
        if self.tools is None and "tools" in self.model_fields_set:
            _dict['tools'] = None

        # set to None if sub_agents (nullable) is None
        # and model_fields_set contains the field
        if self.sub_agents is None and "sub_agents" in self.model_fields_set:
            _dict['sub_agents'] = None

        # set to None if models (nullable) is None
        # and model_fields_set contains the field
        if self.models is None and "models" in self.model_fields_set:
            _dict['models'] = None

        # set to None if data_sources (nullable) is None
        # and model_fields_set contains the field
        if self.data_sources is None and "data_sources" in self.model_fields_set:
            _dict['data_sources'] = None

        # set to None if num_spans (nullable) is None
        # and model_fields_set contains the field
        if self.num_spans is None and "num_spans" in self.model_fields_set:
            _dict['num_spans'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrichedTaskResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "is_autocreated": obj.get("is_autocreated") if obj.get("is_autocreated") is not None else False,
            "creation_source": AgentCreationSource.from_dict(obj["creation_source"]) if obj.get("creation_source") is not None else None,
            "last_fetched": obj.get("last_fetched"),
            "tools": [Tool.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None,
            "sub_agents": [SubAgent.from_dict(_item) for _item in obj["sub_agents"]] if obj.get("sub_agents") is not None else None,
            "models": [LLMModel.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "data_sources": [DataSource.from_dict(_item) for _item in obj["data_sources"]] if obj.get("data_sources") is not None else None,
            "num_spans": obj.get("num_spans"),
            "rules": [RuleResponse.from_dict(_item) for _item in obj["rules"]] if obj.get("rules") is not None else None
        })
        return _obj


