# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.external_rule_result import ExternalRuleResult
from arthur_genai_client.models.rule_result_enum import RuleResultEnum
from typing import Optional, Set
from typing_extensions import Self

class ExternalInferenceResponse(BaseModel):
    """
    ExternalInferenceResponse
    """ # noqa: E501
    id: StrictStr
    inference_id: StrictStr
    result: RuleResultEnum
    created_at: StrictInt
    updated_at: StrictInt
    message: StrictStr
    context: Optional[StrictStr] = None
    response_rule_results: List[ExternalRuleResult]
    tokens: Optional[StrictInt] = None
    model_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "inference_id", "result", "created_at", "updated_at", "message", "context", "response_rule_results", "tokens", "model_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalInferenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in response_rule_results (list)
        _items = []
        if self.response_rule_results:
            for _item_response_rule_results in self.response_rule_results:
                if _item_response_rule_results:
                    _items.append(_item_response_rule_results.to_dict())
            _dict['response_rule_results'] = _items
        # set to None if context (nullable) is None
        # and model_fields_set contains the field
        if self.context is None and "context" in self.model_fields_set:
            _dict['context'] = None

        # set to None if tokens (nullable) is None
        # and model_fields_set contains the field
        if self.tokens is None and "tokens" in self.model_fields_set:
            _dict['tokens'] = None

        # set to None if model_name (nullable) is None
        # and model_fields_set contains the field
        if self.model_name is None and "model_name" in self.model_fields_set:
            _dict['model_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalInferenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "inference_id": obj.get("inference_id"),
            "result": obj.get("result"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "message": obj.get("message"),
            "context": obj.get("context"),
            "response_rule_results": [ExternalRuleResult.from_dict(_item) for _item in obj["response_rule_results"]] if obj.get("response_rule_results") is not None else None,
            "tokens": obj.get("tokens"),
            "model_name": obj.get("model_name")
        })
        return _obj


