# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.external_inference_prompt import ExternalInferencePrompt
from arthur_genai_client.models.external_inference_response import ExternalInferenceResponse
from arthur_genai_client.models.inference_feedback_response import InferenceFeedbackResponse
from arthur_genai_client.models.rule_result_enum import RuleResultEnum
from typing import Optional, Set
from typing_extensions import Self

class ExternalInference(BaseModel):
    """
    ExternalInference
    """ # noqa: E501
    id: StrictStr
    result: RuleResultEnum
    created_at: StrictInt
    updated_at: StrictInt
    task_id: Optional[StrictStr] = None
    task_name: Optional[StrictStr] = None
    conversation_id: Optional[StrictStr] = None
    inference_prompt: ExternalInferencePrompt
    inference_response: Optional[ExternalInferenceResponse] = None
    inference_feedback: List[InferenceFeedbackResponse]
    user_id: Optional[StrictStr] = None
    model_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "result", "created_at", "updated_at", "task_id", "task_name", "conversation_id", "inference_prompt", "inference_response", "inference_feedback", "user_id", "model_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExternalInference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inference_prompt
        if self.inference_prompt:
            _dict['inference_prompt'] = self.inference_prompt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of inference_response
        if self.inference_response:
            _dict['inference_response'] = self.inference_response.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in inference_feedback (list)
        _items = []
        if self.inference_feedback:
            for _item_inference_feedback in self.inference_feedback:
                if _item_inference_feedback:
                    _items.append(_item_inference_feedback.to_dict())
            _dict['inference_feedback'] = _items
        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict['task_id'] = None

        # set to None if task_name (nullable) is None
        # and model_fields_set contains the field
        if self.task_name is None and "task_name" in self.model_fields_set:
            _dict['task_name'] = None

        # set to None if conversation_id (nullable) is None
        # and model_fields_set contains the field
        if self.conversation_id is None and "conversation_id" in self.model_fields_set:
            _dict['conversation_id'] = None

        # set to None if inference_response (nullable) is None
        # and model_fields_set contains the field
        if self.inference_response is None and "inference_response" in self.model_fields_set:
            _dict['inference_response'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if model_name (nullable) is None
        # and model_fields_set contains the field
        if self.model_name is None and "model_name" in self.model_fields_set:
            _dict['model_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExternalInference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "result": obj.get("result"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "task_id": obj.get("task_id"),
            "task_name": obj.get("task_name"),
            "conversation_id": obj.get("conversation_id"),
            "inference_prompt": ExternalInferencePrompt.from_dict(obj["inference_prompt"]) if obj.get("inference_prompt") is not None else None,
            "inference_response": ExternalInferenceResponse.from_dict(obj["inference_response"]) if obj.get("inference_response") is not None else None,
            "inference_feedback": [InferenceFeedbackResponse.from_dict(_item) for _item in obj["inference_feedback"]] if obj.get("inference_feedback") is not None else None,
            "user_id": obj.get("user_id"),
            "model_name": obj.get("model_name")
        })
        return _obj


