# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GCPAgentCreationSource(BaseModel):
    """
    Creation source for GCP-discovered agents.
    """ # noqa: E501
    type: Optional[StrictStr] = 'GCP'
    gcp_project_id: StrictStr = Field(description="GCP project ID")
    gcp_region: StrictStr = Field(description="GCP region")
    gcp_reasoning_engine_id: StrictStr = Field(description="GCP Vertex AI Reasoning Engine ID")
    service_names: Optional[List[StrictStr]] = Field(default=None, description="Service names associated with this agent")
    __properties: ClassVar[List[str]] = ["type", "gcp_project_id", "gcp_region", "gcp_reasoning_engine_id", "service_names"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GCP']):
            raise ValueError("must be one of enum values ('GCP')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GCPAgentCreationSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GCPAgentCreationSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'GCP',
            "gcp_project_id": obj.get("gcp_project_id"),
            "gcp_region": obj.get("gcp_region"),
            "gcp_reasoning_engine_id": obj.get("gcp_reasoning_engine_id"),
            "service_names": obj.get("service_names")
        })
        return _obj


