# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from arthur_genai_client.models.rag_search_setting_configuration_response import RagSearchSettingConfigurationResponse
from typing import Optional, Set
from typing_extensions import Self

class ListRagSearchSettingConfigurationsResponse(BaseModel):
    """
    ListRagSearchSettingConfigurationsResponse
    """ # noqa: E501
    count: StrictInt = Field(description="The total number of RAG search setting configurations matching the parameters.")
    rag_provider_setting_configurations: List[RagSearchSettingConfigurationResponse] = Field(description="List of RAG search setting configurations matching the search filters. Length is less than or equal to page_size parameter")
    __properties: ClassVar[List[str]] = ["count", "rag_provider_setting_configurations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListRagSearchSettingConfigurationsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rag_provider_setting_configurations (list)
        _items = []
        if self.rag_provider_setting_configurations:
            for _item_rag_provider_setting_configurations in self.rag_provider_setting_configurations:
                if _item_rag_provider_setting_configurations:
                    _items.append(_item_rag_provider_setting_configurations.to_dict())
            _dict['rag_provider_setting_configurations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListRagSearchSettingConfigurationsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "rag_provider_setting_configurations": [RagSearchSettingConfigurationResponse.from_dict(_item) for _item in obj["rag_provider_setting_configurations"]] if obj.get("rag_provider_setting_configurations") is not None else None
        })
        return _obj


