# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.model_provider import ModelProvider
from typing import Optional, Set
from typing_extensions import Self

class LLMVersionResponse(BaseModel):
    """
    LLMVersionResponse
    """ # noqa: E501
    version: StrictInt = Field(description="Version number of the llm eval")
    created_at: datetime = Field(description="Timestamp when the llm eval version was created")
    deleted_at: Optional[datetime]
    model_provider: ModelProvider = Field(description="Model provider chosen for this version of the llm eval")
    model_name: StrictStr = Field(description="Model name chosen for this version of the llm eval")
    tags: Optional[List[StrictStr]] = Field(default=None, description="List of tags for the llm asset")
    __properties: ClassVar[List[str]] = ["version", "created_at", "deleted_at", "model_provider", "model_name", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LLMVersionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LLMVersionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "created_at": obj.get("created_at"),
            "deleted_at": obj.get("deleted_at"),
            "model_provider": obj.get("model_provider"),
            "model_name": obj.get("model_name"),
            "tags": obj.get("tags")
        })
        return _obj


