# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class LLMGetAllMetadataResponse(BaseModel):
    """
    LLMGetAllMetadataResponse
    """  # noqa: E501

    name: StrictStr = Field(description="Name of the llm asset")
    versions: StrictInt = Field(description="Number of versions of the llm asset")
    tags: Optional[List[StrictStr]] = Field(
        default=None, description="List of tags for the llm asset"
    )
    created_at: datetime = Field(description="Timestamp when the llm asset was created")
    latest_version_created_at: datetime = Field(
        description="Timestamp when the last version of the llm asset was created"
    )
    deleted_versions: List[StrictInt] = Field(
        description="List of deleted versions of the llm asset"
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "versions",
        "tags",
        "created_at",
        "latest_version_created_at",
        "deleted_versions",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LLMGetAllMetadataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LLMGetAllMetadataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "versions": obj.get("versions"),
                "tags": obj.get("tags"),
                "created_at": obj.get("created_at"),
                "latest_version_created_at": obj.get("latest_version_created_at"),
                "deleted_versions": obj.get("deleted_versions"),
            }
        )
        return _obj
