# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.create_prompt_experiment_request_prompt_configs_inner import CreatePromptExperimentRequestPromptConfigsInner
from arthur_genai_client.models.dataset_ref import DatasetRef
from arthur_genai_client.models.eval_ref_output import EvalRefOutput
from arthur_genai_client.models.new_dataset_version_row_column_item_request import NewDatasetVersionRowColumnItemRequest
from arthur_genai_client.models.prompt_variable_mapping_output import PromptVariableMappingOutput
from typing import Optional, Set
from typing_extensions import Self

class NotebookStateOutput(BaseModel):
    """
    Draft state of a notebook - mirrors experiment config but all fields optional.
    """ # noqa: E501
    prompt_configs: Optional[List[CreatePromptExperimentRequestPromptConfigsInner]] = None
    prompt_variable_mapping: Optional[List[PromptVariableMappingOutput]] = None
    dataset_ref: Optional[DatasetRef] = None
    dataset_row_filter: Optional[List[NewDatasetVersionRowColumnItemRequest]] = None
    eval_list: Optional[List[EvalRefOutput]] = None
    __properties: ClassVar[List[str]] = ["prompt_configs", "prompt_variable_mapping", "dataset_ref", "dataset_row_filter", "eval_list"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotebookStateOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in prompt_configs (list)
        _items = []
        if self.prompt_configs:
            for _item_prompt_configs in self.prompt_configs:
                if _item_prompt_configs:
                    _items.append(_item_prompt_configs.to_dict())
            _dict['prompt_configs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in prompt_variable_mapping (list)
        _items = []
        if self.prompt_variable_mapping:
            for _item_prompt_variable_mapping in self.prompt_variable_mapping:
                if _item_prompt_variable_mapping:
                    _items.append(_item_prompt_variable_mapping.to_dict())
            _dict['prompt_variable_mapping'] = _items
        # override the default output from pydantic by calling `to_dict()` of dataset_ref
        if self.dataset_ref:
            _dict['dataset_ref'] = self.dataset_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in dataset_row_filter (list)
        _items = []
        if self.dataset_row_filter:
            for _item_dataset_row_filter in self.dataset_row_filter:
                if _item_dataset_row_filter:
                    _items.append(_item_dataset_row_filter.to_dict())
            _dict['dataset_row_filter'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in eval_list (list)
        _items = []
        if self.eval_list:
            for _item_eval_list in self.eval_list:
                if _item_eval_list:
                    _items.append(_item_eval_list.to_dict())
            _dict['eval_list'] = _items
        # set to None if prompt_configs (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_configs is None and "prompt_configs" in self.model_fields_set:
            _dict['prompt_configs'] = None

        # set to None if prompt_variable_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_variable_mapping is None and "prompt_variable_mapping" in self.model_fields_set:
            _dict['prompt_variable_mapping'] = None

        # set to None if dataset_ref (nullable) is None
        # and model_fields_set contains the field
        if self.dataset_ref is None and "dataset_ref" in self.model_fields_set:
            _dict['dataset_ref'] = None

        # set to None if dataset_row_filter (nullable) is None
        # and model_fields_set contains the field
        if self.dataset_row_filter is None and "dataset_row_filter" in self.model_fields_set:
            _dict['dataset_row_filter'] = None

        # set to None if eval_list (nullable) is None
        # and model_fields_set contains the field
        if self.eval_list is None and "eval_list" in self.model_fields_set:
            _dict['eval_list'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotebookStateOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prompt_configs": [CreatePromptExperimentRequestPromptConfigsInner.from_dict(_item) for _item in obj["prompt_configs"]] if obj.get("prompt_configs") is not None else None,
            "prompt_variable_mapping": [PromptVariableMappingOutput.from_dict(_item) for _item in obj["prompt_variable_mapping"]] if obj.get("prompt_variable_mapping") is not None else None,
            "dataset_ref": DatasetRef.from_dict(obj["dataset_ref"]) if obj.get("dataset_ref") is not None else None,
            "dataset_row_filter": [NewDatasetVersionRowColumnItemRequest.from_dict(_item) for _item in obj["dataset_row_filter"]] if obj.get("dataset_row_filter") is not None else None,
            "eval_list": [EvalRefOutput.from_dict(_item) for _item in obj["eval_list"]] if obj.get("eval_list") is not None else None
        })
        return _obj


