# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.experiment_status import ExperimentStatus
from typing import Optional, Set
from typing_extensions import Self

class NotebookSummary(BaseModel):
    """
    Summary of a notebook
    """ # noqa: E501
    id: StrictStr = Field(description="Notebook ID")
    task_id: StrictStr = Field(description="Associated task ID")
    name: StrictStr = Field(description="Notebook name")
    description: Optional[StrictStr] = None
    created_at: StrictStr = Field(description="ISO timestamp when created")
    updated_at: StrictStr = Field(description="ISO timestamp when last updated")
    run_count: StrictInt = Field(description="Number of experiments run from this notebook")
    latest_run_id: Optional[StrictStr] = None
    latest_run_status: Optional[ExperimentStatus] = None
    __properties: ClassVar[List[str]] = ["id", "task_id", "name", "description", "created_at", "updated_at", "run_count", "latest_run_id", "latest_run_status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotebookSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if latest_run_id (nullable) is None
        # and model_fields_set contains the field
        if self.latest_run_id is None and "latest_run_id" in self.model_fields_set:
            _dict['latest_run_id'] = None

        # set to None if latest_run_status (nullable) is None
        # and model_fields_set contains the field
        if self.latest_run_status is None and "latest_run_status" in self.model_fields_set:
            _dict['latest_run_status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotebookSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "task_id": obj.get("task_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "run_count": obj.get("run_count"),
            "latest_run_id": obj.get("latest_run_id"),
            "latest_run_status": obj.get("latest_run_status")
        })
        return _obj


