# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, SecretStr, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.gcp_service_account_credentials_request import GCPServiceAccountCredentialsRequest
from typing import Optional, Set
from typing_extensions import Self

class PutModelProviderCredentials(BaseModel):
    """
    PutModelProviderCredentials
    """ # noqa: E501
    api_key: Optional[SecretStr] = None
    project_id: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    aws_access_key_id: Optional[SecretStr] = None
    aws_secret_access_key: Optional[SecretStr] = None
    aws_bedrock_runtime_endpoint: Optional[SecretStr] = None
    aws_role_name: Optional[SecretStr] = None
    aws_session_name: Optional[SecretStr] = None
    api_base: Optional[SecretStr] = None
    credentials_file: Optional[GCPServiceAccountCredentialsRequest] = None
    __properties: ClassVar[List[str]] = ["api_key", "project_id", "region", "aws_access_key_id", "aws_secret_access_key", "aws_bedrock_runtime_endpoint", "aws_role_name", "aws_session_name", "api_base", "credentials_file"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PutModelProviderCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of credentials_file
        if self.credentials_file:
            _dict['credentials_file'] = self.credentials_file.to_dict()
        # set to None if api_key (nullable) is None
        # and model_fields_set contains the field
        if self.api_key is None and "api_key" in self.model_fields_set:
            _dict['api_key'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if aws_access_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.aws_access_key_id is None and "aws_access_key_id" in self.model_fields_set:
            _dict['aws_access_key_id'] = None

        # set to None if aws_secret_access_key (nullable) is None
        # and model_fields_set contains the field
        if self.aws_secret_access_key is None and "aws_secret_access_key" in self.model_fields_set:
            _dict['aws_secret_access_key'] = None

        # set to None if aws_bedrock_runtime_endpoint (nullable) is None
        # and model_fields_set contains the field
        if self.aws_bedrock_runtime_endpoint is None and "aws_bedrock_runtime_endpoint" in self.model_fields_set:
            _dict['aws_bedrock_runtime_endpoint'] = None

        # set to None if aws_role_name (nullable) is None
        # and model_fields_set contains the field
        if self.aws_role_name is None and "aws_role_name" in self.model_fields_set:
            _dict['aws_role_name'] = None

        # set to None if aws_session_name (nullable) is None
        # and model_fields_set contains the field
        if self.aws_session_name is None and "aws_session_name" in self.model_fields_set:
            _dict['aws_session_name'] = None

        # set to None if api_base (nullable) is None
        # and model_fields_set contains the field
        if self.api_base is None and "api_base" in self.model_fields_set:
            _dict['api_base'] = None

        # set to None if credentials_file (nullable) is None
        # and model_fields_set contains the field
        if self.credentials_file is None and "credentials_file" in self.model_fields_set:
            _dict['credentials_file'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PutModelProviderCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key": obj.get("api_key"),
            "project_id": obj.get("project_id"),
            "region": obj.get("region"),
            "aws_access_key_id": obj.get("aws_access_key_id"),
            "aws_secret_access_key": obj.get("aws_secret_access_key"),
            "aws_bedrock_runtime_endpoint": obj.get("aws_bedrock_runtime_endpoint"),
            "aws_role_name": obj.get("aws_role_name"),
            "aws_session_name": obj.get("aws_session_name"),
            "api_base": obj.get("api_base"),
            "credentials_file": GCPServiceAccountCredentialsRequest.from_dict(obj["credentials_file"]) if obj.get("credentials_file") is not None else None
        })
        return _obj


