# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.rag_result import RagResult
from arthur_genai_client.models.test_case_status import TestCaseStatus
from typing import Optional, Set
from typing_extensions import Self

class RagTestCase(BaseModel):
    """
    Individual test case result for RAG experiment
    """ # noqa: E501
    status: TestCaseStatus = Field(description="Status of the test case")
    dataset_row_id: StrictStr = Field(description="ID of the dataset row")
    total_cost: Optional[StrictStr] = None
    rag_results: List[RagResult] = Field(description="Results for each RAG configuration tested")
    __properties: ClassVar[List[str]] = ["status", "dataset_row_id", "total_cost", "rag_results"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RagTestCase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rag_results (list)
        _items = []
        if self.rag_results:
            for _item_rag_results in self.rag_results:
                if _item_rag_results:
                    _items.append(_item_rag_results.to_dict())
            _dict['rag_results'] = _items
        # set to None if total_cost (nullable) is None
        # and model_fields_set contains the field
        if self.total_cost is None and "total_cost" in self.model_fields_set:
            _dict['total_cost'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RagTestCase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "dataset_row_id": obj.get("dataset_row_id"),
            "total_cost": obj.get("total_cost"),
            "rag_results": [RagResult.from_dict(_item) for _item in obj["rag_results"]] if obj.get("rag_results") is not None else None
        })
        return _obj


