# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class RagAPIKeyAuthenticationProviderEnum(str, Enum):
    """
    RagAPIKeyAuthenticationProviderEnum
    """

    """
    allowed enum values
    """
    WEAVIATE = "weaviate"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RagAPIKeyAuthenticationProviderEnum from a JSON string"""
        return cls(json.loads(json_str))
