# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self

from arthur_genai_client.models.regex_span_response import RegexSpanResponse


class RegexDetailsResponse(BaseModel):
    """
    RegexDetailsResponse
    """  # noqa: E501

    score: Optional[StrictBool] = None
    message: Optional[StrictStr] = None
    regex_matches: Optional[List[RegexSpanResponse]] = Field(
        default=None,
        description="Each string in this list corresponds to a matching span from the input text that matches the configured regex rule.",
    )
    __properties: ClassVar[List[str]] = ["score", "message", "regex_matches"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegexDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in regex_matches (list)
        _items = []
        if self.regex_matches:
            for _item_regex_matches in self.regex_matches:
                if _item_regex_matches:
                    _items.append(_item_regex_matches.to_dict())
            _dict["regex_matches"] = _items
        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict["score"] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict["message"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegexDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "score": obj.get("score"),
                "message": obj.get("message"),
                "regex_matches": (
                    [RegexSpanResponse.from_dict(_item) for _item in obj["regex_matches"]]
                    if obj.get("regex_matches") is not None
                    else None
                ),
            }
        )
        return _obj
