# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arthur_genai_client.models.rule_scope import RuleScope
from arthur_genai_client.models.rule_type import RuleType
from typing import Optional, Set
from typing_extensions import Self

class SearchRulesRequest(BaseModel):
    """
    SearchRulesRequest
    """ # noqa: E501
    rule_ids: Optional[List[StrictStr]] = None
    rule_scopes: Optional[List[RuleScope]] = None
    prompt_enabled: Optional[StrictBool] = None
    response_enabled: Optional[StrictBool] = None
    rule_types: Optional[List[RuleType]] = None
    __properties: ClassVar[List[str]] = ["rule_ids", "rule_scopes", "prompt_enabled", "response_enabled", "rule_types"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchRulesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rule_ids (nullable) is None
        # and model_fields_set contains the field
        if self.rule_ids is None and "rule_ids" in self.model_fields_set:
            _dict['rule_ids'] = None

        # set to None if rule_scopes (nullable) is None
        # and model_fields_set contains the field
        if self.rule_scopes is None and "rule_scopes" in self.model_fields_set:
            _dict['rule_scopes'] = None

        # set to None if prompt_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_enabled is None and "prompt_enabled" in self.model_fields_set:
            _dict['prompt_enabled'] = None

        # set to None if response_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.response_enabled is None and "response_enabled" in self.model_fields_set:
            _dict['response_enabled'] = None

        # set to None if rule_types (nullable) is None
        # and model_fields_set contains the field
        if self.rule_types is None and "rule_types" in self.model_fields_set:
            _dict['rule_types'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchRulesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rule_ids": obj.get("rule_ids"),
            "rule_scopes": obj.get("rule_scopes"),
            "prompt_enabled": obj.get("prompt_enabled"),
            "response_enabled": obj.get("response_enabled"),
            "rule_types": obj.get("rule_types")
        })
        return _obj


