# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.424
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SearchTasksRequest(BaseModel):
    """
    SearchTasksRequest
    """ # noqa: E501
    task_ids: Optional[List[StrictStr]] = None
    task_name: Optional[StrictStr] = None
    is_agentic: Optional[StrictBool] = None
    include_archived: Optional[StrictBool] = None
    only_archived: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["task_ids", "task_name", "is_agentic", "include_archived", "only_archived"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchTasksRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if task_ids (nullable) is None
        # and model_fields_set contains the field
        if self.task_ids is None and "task_ids" in self.model_fields_set:
            _dict['task_ids'] = None

        # set to None if task_name (nullable) is None
        # and model_fields_set contains the field
        if self.task_name is None and "task_name" in self.model_fields_set:
            _dict['task_name'] = None

        # set to None if is_agentic (nullable) is None
        # and model_fields_set contains the field
        if self.is_agentic is None and "is_agentic" in self.model_fields_set:
            _dict['is_agentic'] = None

        # set to None if include_archived (nullable) is None
        # and model_fields_set contains the field
        if self.include_archived is None and "include_archived" in self.model_fields_set:
            _dict['include_archived'] = None

        # set to None if only_archived (nullable) is None
        # and model_fields_set contains the field
        if self.only_archived is None and "only_archived" in self.model_fields_set:
            _dict['only_archived'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchTasksRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_ids": obj.get("task_ids"),
            "task_name": obj.get("task_name"),
            "is_agentic": obj.get("is_agentic"),
            "include_archived": obj.get("include_archived"),
            "only_archived": obj.get("only_archived")
        })
        return _obj


