# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Dict, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing_extensions import Self

from arthur_genai_client.models.dataset_column_variable_source import (
    DatasetColumnVariableSource,
)
from arthur_genai_client.models.generated_variable_source import GeneratedVariableSource
from arthur_genai_client.models.request_time_parameter_source import (
    RequestTimeParameterSource,
)

SOURCE2_ONE_OF_SCHEMAS = [
    "DatasetColumnVariableSource",
    "GeneratedVariableSource",
    "RequestTimeParameterSource",
]


class Source2(BaseModel):
    """
    Source of the variable value
    """

    # data type: DatasetColumnVariableSource
    oneof_schema_1_validator: Optional[DatasetColumnVariableSource] = None
    # data type: RequestTimeParameterSource
    oneof_schema_2_validator: Optional[RequestTimeParameterSource] = None
    # data type: GeneratedVariableSource
    oneof_schema_3_validator: Optional[GeneratedVariableSource] = None
    actual_instance: Optional[
        Union[DatasetColumnVariableSource, GeneratedVariableSource, RequestTimeParameterSource]
    ] = None
    one_of_schemas: Set[str] = {
        "DatasetColumnVariableSource",
        "GeneratedVariableSource",
        "RequestTimeParameterSource",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = Source2.model_construct()
        error_messages = []
        match = 0
        # validate data type: DatasetColumnVariableSource
        if not isinstance(v, DatasetColumnVariableSource):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DatasetColumnVariableSource`"
            )
        else:
            match += 1
        # validate data type: RequestTimeParameterSource
        if not isinstance(v, RequestTimeParameterSource):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `RequestTimeParameterSource`"
            )
        else:
            match += 1
        # validate data type: GeneratedVariableSource
        if not isinstance(v, GeneratedVariableSource):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeneratedVariableSource`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in Source2 with oneOf schemas: DatasetColumnVariableSource, GeneratedVariableSource, RequestTimeParameterSource. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in Source2 with oneOf schemas: DatasetColumnVariableSource, GeneratedVariableSource, RequestTimeParameterSource. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DatasetColumnVariableSource
        try:
            instance.actual_instance = DatasetColumnVariableSource.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestTimeParameterSource
        try:
            instance.actual_instance = RequestTimeParameterSource.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeneratedVariableSource
        try:
            instance.actual_instance = GeneratedVariableSource.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into Source2 with oneOf schemas: DatasetColumnVariableSource, GeneratedVariableSource, RequestTimeParameterSource. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into Source2 with oneOf schemas: DatasetColumnVariableSource, GeneratedVariableSource, RequestTimeParameterSource. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[
            Dict[str, Any],
            DatasetColumnVariableSource,
            GeneratedVariableSource,
            RequestTimeParameterSource,
        ]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
