# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self

from arthur_genai_client.models.metric_result_response import MetricResultResponse


class SpanWithMetricsResponse(BaseModel):
    """
    SpanWithMetricsResponse
    """  # noqa: E501

    prompt_token_count: Optional[StrictInt] = None
    completion_token_count: Optional[StrictInt] = None
    total_token_count: Optional[StrictInt] = None
    prompt_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    completion_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    total_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    id: StrictStr
    trace_id: StrictStr
    span_id: StrictStr
    parent_span_id: Optional[StrictStr] = None
    span_kind: Optional[StrictStr] = None
    span_name: Optional[StrictStr] = None
    start_time: datetime
    end_time: datetime
    task_id: Optional[StrictStr] = None
    session_id: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    status_code: StrictStr = Field(description="Status code for the span (Unset, Error, Ok)")
    created_at: datetime
    updated_at: datetime
    raw_data: Dict[str, Any]
    input_content: Optional[StrictStr] = None
    output_content: Optional[StrictStr] = None
    metric_results: Optional[List[MetricResultResponse]] = Field(
        default=None, description="List of metric results for this span"
    )
    __properties: ClassVar[List[str]] = [
        "prompt_token_count",
        "completion_token_count",
        "total_token_count",
        "prompt_token_cost",
        "completion_token_cost",
        "total_token_cost",
        "id",
        "trace_id",
        "span_id",
        "parent_span_id",
        "span_kind",
        "span_name",
        "start_time",
        "end_time",
        "task_id",
        "session_id",
        "user_id",
        "status_code",
        "created_at",
        "updated_at",
        "raw_data",
        "input_content",
        "output_content",
        "metric_results",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpanWithMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in metric_results (list)
        _items = []
        if self.metric_results:
            for _item_metric_results in self.metric_results:
                if _item_metric_results:
                    _items.append(_item_metric_results.to_dict())
            _dict["metric_results"] = _items
        # set to None if prompt_token_count (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_token_count is None and "prompt_token_count" in self.model_fields_set:
            _dict["prompt_token_count"] = None

        # set to None if completion_token_count (nullable) is None
        # and model_fields_set contains the field
        if (
            self.completion_token_count is None
            and "completion_token_count" in self.model_fields_set
        ):
            _dict["completion_token_count"] = None

        # set to None if total_token_count (nullable) is None
        # and model_fields_set contains the field
        if self.total_token_count is None and "total_token_count" in self.model_fields_set:
            _dict["total_token_count"] = None

        # set to None if prompt_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_token_cost is None and "prompt_token_cost" in self.model_fields_set:
            _dict["prompt_token_cost"] = None

        # set to None if completion_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.completion_token_cost is None and "completion_token_cost" in self.model_fields_set:
            _dict["completion_token_cost"] = None

        # set to None if total_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.total_token_cost is None and "total_token_cost" in self.model_fields_set:
            _dict["total_token_cost"] = None

        # set to None if parent_span_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_span_id is None and "parent_span_id" in self.model_fields_set:
            _dict["parent_span_id"] = None

        # set to None if span_kind (nullable) is None
        # and model_fields_set contains the field
        if self.span_kind is None and "span_kind" in self.model_fields_set:
            _dict["span_kind"] = None

        # set to None if span_name (nullable) is None
        # and model_fields_set contains the field
        if self.span_name is None and "span_name" in self.model_fields_set:
            _dict["span_name"] = None

        # set to None if task_id (nullable) is None
        # and model_fields_set contains the field
        if self.task_id is None and "task_id" in self.model_fields_set:
            _dict["task_id"] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict["session_id"] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict["user_id"] = None

        # set to None if input_content (nullable) is None
        # and model_fields_set contains the field
        if self.input_content is None and "input_content" in self.model_fields_set:
            _dict["input_content"] = None

        # set to None if output_content (nullable) is None
        # and model_fields_set contains the field
        if self.output_content is None and "output_content" in self.model_fields_set:
            _dict["output_content"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpanWithMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "prompt_token_count": obj.get("prompt_token_count"),
                "completion_token_count": obj.get("completion_token_count"),
                "total_token_count": obj.get("total_token_count"),
                "prompt_token_cost": obj.get("prompt_token_cost"),
                "completion_token_cost": obj.get("completion_token_cost"),
                "total_token_cost": obj.get("total_token_cost"),
                "id": obj.get("id"),
                "trace_id": obj.get("trace_id"),
                "span_id": obj.get("span_id"),
                "parent_span_id": obj.get("parent_span_id"),
                "span_kind": obj.get("span_kind"),
                "span_name": obj.get("span_name"),
                "start_time": obj.get("start_time"),
                "end_time": obj.get("end_time"),
                "task_id": obj.get("task_id"),
                "session_id": obj.get("session_id"),
                "user_id": obj.get("user_id"),
                "status_code": obj.get("status_code"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "raw_data": obj.get("raw_data"),
                "input_content": obj.get("input_content"),
                "output_content": obj.get("output_content"),
                "metric_results": (
                    [MetricResultResponse.from_dict(_item) for _item in obj["metric_results"]]
                    if obj.get("metric_results") is not None
                    else None
                ),
            }
        )
        return _obj
