# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from arthur_genai_client.models.llm_request_config_settings import (
    LLMRequestConfigSettings,
)
from arthur_genai_client.models.model_provider import ModelProvider
from arthur_genai_client.models.new_dataset_version_row_request import (
    NewDatasetVersionRowRequest,
)
from arthur_genai_client.models.open_ai_message_input import OpenAIMessageInput
from arthur_genai_client.models.synthetic_data_column_description import (
    SyntheticDataColumnDescription,
)


class SyntheticDataConversationRequest(BaseModel):
    """
    Request for continuing a synthetic data generation conversation.
    """  # noqa: E501

    message: StrictStr = Field(
        description="User's message/instruction for refining the generated data."
    )
    current_rows: List[NewDatasetVersionRowRequest] = Field(
        description="Current state of generated rows (including any manual edits)."
    )
    conversation_history: List[OpenAIMessageInput] = Field(
        description="Previous conversation messages for context."
    )
    dataset_purpose: StrictStr = Field(description="Original dataset purpose for context.")
    column_descriptions: List[SyntheticDataColumnDescription] = Field(
        description="Original column descriptions for context."
    )
    model_provider: ModelProvider = Field(
        description="Provider of the LLM model to use for generation."
    )
    model_name: StrictStr = Field(description="Name of the LLM model to use for generation.")
    config: Optional[LLMRequestConfigSettings] = None
    __properties: ClassVar[List[str]] = [
        "message",
        "current_rows",
        "conversation_history",
        "dataset_purpose",
        "column_descriptions",
        "model_provider",
        "model_name",
        "config",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SyntheticDataConversationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in current_rows (list)
        _items = []
        if self.current_rows:
            for _item_current_rows in self.current_rows:
                if _item_current_rows:
                    _items.append(_item_current_rows.to_dict())
            _dict["current_rows"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in conversation_history (list)
        _items = []
        if self.conversation_history:
            for _item_conversation_history in self.conversation_history:
                if _item_conversation_history:
                    _items.append(_item_conversation_history.to_dict())
            _dict["conversation_history"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in column_descriptions (list)
        _items = []
        if self.column_descriptions:
            for _item_column_descriptions in self.column_descriptions:
                if _item_column_descriptions:
                    _items.append(_item_column_descriptions.to_dict())
            _dict["column_descriptions"] = _items
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict["config"] = self.config.to_dict()
        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict["config"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SyntheticDataConversationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "message": obj.get("message"),
                "current_rows": (
                    [NewDatasetVersionRowRequest.from_dict(_item) for _item in obj["current_rows"]]
                    if obj.get("current_rows") is not None
                    else None
                ),
                "conversation_history": (
                    [OpenAIMessageInput.from_dict(_item) for _item in obj["conversation_history"]]
                    if obj.get("conversation_history") is not None
                    else None
                ),
                "dataset_purpose": obj.get("dataset_purpose"),
                "column_descriptions": (
                    [
                        SyntheticDataColumnDescription.from_dict(_item)
                        for _item in obj["column_descriptions"]
                    ]
                    if obj.get("column_descriptions") is not None
                    else None
                ),
                "model_provider": obj.get("model_provider"),
                "model_name": obj.get("model_name"),
                "config": (
                    LLMRequestConfigSettings.from_dict(obj["config"])
                    if obj.get("config") is not None
                    else None
                ),
            }
        )
        return _obj
