# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing_extensions import Self


class TokenUsageCount(BaseModel):
    """
    TokenUsageCount
    """  # noqa: E501

    inference: StrictInt = Field(description="Number of inference tokens sent to Arthur.")
    eval_prompt: StrictInt = Field(description="Number of Prompt tokens incurred by Arthur rules.")
    eval_completion: StrictInt = Field(
        description="Number of Completion tokens incurred by Arthur rules."
    )
    user_input: StrictInt = Field(
        description="Number of user input tokens sent to Arthur. This field is deprecated and will be removed in the future. Use inference instead."
    )
    prompt: StrictInt = Field(
        description="Number of Prompt tokens incurred by Arthur rules. This field is deprecated and will be removed in the future. Use eval_prompt instead."
    )
    completion: StrictInt = Field(
        description="Number of Completion tokens incurred by Arthur rules. This field is deprecated and will be removed in the future. Use eval_completion instead."
    )
    __properties: ClassVar[List[str]] = [
        "inference",
        "eval_prompt",
        "eval_completion",
        "user_input",
        "prompt",
        "completion",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenUsageCount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenUsageCount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "inference": obj.get("inference"),
                "eval_prompt": obj.get("eval_prompt"),
                "eval_completion": obj.get("eval_completion"),
                "user_input": obj.get("user_input"),
                "prompt": obj.get("prompt"),
                "completion": obj.get("completion"),
            }
        )
        return _obj
