# coding: utf-8

"""
Arthur GenAI Engine

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.424
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self

from arthur_genai_client.models.agentic_annotation_response import (
    AgenticAnnotationResponse,
)
from arthur_genai_client.models.nested_span_with_metrics_response import (
    NestedSpanWithMetricsResponse,
)


class TraceResponse(BaseModel):
    """
    Response model for a single trace containing nested spans
    """  # noqa: E501

    prompt_token_count: Optional[StrictInt] = None
    completion_token_count: Optional[StrictInt] = None
    total_token_count: Optional[StrictInt] = None
    prompt_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    completion_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    total_token_cost: Optional[Union[StrictFloat, StrictInt]] = None
    trace_id: StrictStr = Field(description="ID of the trace")
    start_time: datetime = Field(description="Start time of the earliest span in this trace")
    end_time: datetime = Field(description="End time of the latest span in this trace")
    input_content: Optional[StrictStr] = None
    output_content: Optional[StrictStr] = None
    root_spans: Optional[List[NestedSpanWithMetricsResponse]] = Field(
        default=None,
        description="Root spans (spans with no parent) in this trace, with children nested",
    )
    annotations: Optional[List[AgenticAnnotationResponse]] = None
    __properties: ClassVar[List[str]] = [
        "prompt_token_count",
        "completion_token_count",
        "total_token_count",
        "prompt_token_cost",
        "completion_token_cost",
        "total_token_cost",
        "trace_id",
        "start_time",
        "end_time",
        "input_content",
        "output_content",
        "root_spans",
        "annotations",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TraceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in root_spans (list)
        _items = []
        if self.root_spans:
            for _item_root_spans in self.root_spans:
                if _item_root_spans:
                    _items.append(_item_root_spans.to_dict())
            _dict["root_spans"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in annotations (list)
        _items = []
        if self.annotations:
            for _item_annotations in self.annotations:
                if _item_annotations:
                    _items.append(_item_annotations.to_dict())
            _dict["annotations"] = _items
        # set to None if prompt_token_count (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_token_count is None and "prompt_token_count" in self.model_fields_set:
            _dict["prompt_token_count"] = None

        # set to None if completion_token_count (nullable) is None
        # and model_fields_set contains the field
        if (
            self.completion_token_count is None
            and "completion_token_count" in self.model_fields_set
        ):
            _dict["completion_token_count"] = None

        # set to None if total_token_count (nullable) is None
        # and model_fields_set contains the field
        if self.total_token_count is None and "total_token_count" in self.model_fields_set:
            _dict["total_token_count"] = None

        # set to None if prompt_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.prompt_token_cost is None and "prompt_token_cost" in self.model_fields_set:
            _dict["prompt_token_cost"] = None

        # set to None if completion_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.completion_token_cost is None and "completion_token_cost" in self.model_fields_set:
            _dict["completion_token_cost"] = None

        # set to None if total_token_cost (nullable) is None
        # and model_fields_set contains the field
        if self.total_token_cost is None and "total_token_cost" in self.model_fields_set:
            _dict["total_token_cost"] = None

        # set to None if input_content (nullable) is None
        # and model_fields_set contains the field
        if self.input_content is None and "input_content" in self.model_fields_set:
            _dict["input_content"] = None

        # set to None if output_content (nullable) is None
        # and model_fields_set contains the field
        if self.output_content is None and "output_content" in self.model_fields_set:
            _dict["output_content"] = None

        # set to None if annotations (nullable) is None
        # and model_fields_set contains the field
        if self.annotations is None and "annotations" in self.model_fields_set:
            _dict["annotations"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TraceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "prompt_token_count": obj.get("prompt_token_count"),
                "completion_token_count": obj.get("completion_token_count"),
                "total_token_count": obj.get("total_token_count"),
                "prompt_token_cost": obj.get("prompt_token_cost"),
                "completion_token_cost": obj.get("completion_token_cost"),
                "total_token_cost": obj.get("total_token_cost"),
                "trace_id": obj.get("trace_id"),
                "start_time": obj.get("start_time"),
                "end_time": obj.get("end_time"),
                "input_content": obj.get("input_content"),
                "output_content": obj.get("output_content"),
                "root_spans": (
                    [NestedSpanWithMetricsResponse.from_dict(_item) for _item in obj["root_spans"]]
                    if obj.get("root_spans") is not None
                    else None
                ),
                "annotations": (
                    [AgenticAnnotationResponse.from_dict(_item) for _item in obj["annotations"]]
                    if obj.get("annotations") is not None
                    else None
                ),
            }
        )
        return _obj
