{{- if .Values.arthurGenaiEngineHPA.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "arthur-genai-engine.fullname" . }}
  {{- with .Values.arthurGenaiEngineHPA.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: arthur-genai-engine
    {{- include "arthur-genai-engine.labels" . | nindent 4 }}
    {{- with .Values.arthurGenaiEngineHPA.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    {{- if .Values.arthurResourceNameSuffix }}
    name: arthur-genai-engine-{{ .Values.arthurResourceNameSuffix }}
    {{- else }}
    name: arthur-genai-engine
    {{- end }}
  minReplicas: {{ .Values.arthurGenaiEngineHPA.minReplicas }}
  maxReplicas: {{ .Values.arthurGenaiEngineHPA.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.arthurGenaiEngineHPA.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.arthurGenaiEngineHPA.targetMemoryUtilizationPercentage }}
  {{- with .Values.arthurGenaiEngineHPA.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
