apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.arthurResourceNameSuffix }}
  name: arthur-genai-engine-audit-logs-{{ .Values.arthurResourceNameSuffix }}
  {{- else }}
  name: arthur-genai-engine-audit-logs
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.arthurGenaiEngineDeployment.auditLog.storageSize | default "10Gi" }}
  storageClassName: {{ .Values.arthurGenaiEngineDeployment.auditLog.storageClassName }}
