{{- if .Values.genaiEngineServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arthur-genai-engine.serviceAccountName" . }}
  labels:
    {{- include "arthur-genai-engine.labels" . | nindent 4 }}
{{- end }}
