{{- if .Values.mlEngineServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arthur-ml-engine.serviceAccountName" . }}
  labels:
    {{- include "arthur-ml-engine.labels" . | nindent 4 }}
{{- end }}
