AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ArthurResourceNamespace:
    Description: 'A unique namespace for this Arthur stack resources (e.g. arthur1). It should be between 1 and 14 characters long.'
    Type: String
    MinLength: '1'
    MaxLength: '14'
    ConstraintDescription: 'The Arthur platform resources namespace must be 1-14 characters long.'
    Default: 'arthur'
  ArthurResourceNameSuffix:
    Description: 'Name suffix for this Arthur stack resources (e.g. -prod). It should be between 0 and 5 characters long.'
    Type: String
    MinLength: '0'
    MaxLength: '5'
    ConstraintDescription: 'The Arthur platform resources name suffix must be 0-5 characters long.'
    Default: ''
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC to deploy SGs to'
  VPCCidrBlock:
    Type: String
    Description: 'The VPC CIDR block for SGs to use'
  PostgresBYOSecurityGroupIDs:
    Type: CommaDelimitedList
    Description: '(Optional) Security group ID to use for the auto-provisioned Aurora Serverless v2 or the bring-your-own Postgres. If not specified, one will be provisioned.'
    Default: ''

Conditions:
  IsPostgresBYOSecurityGroupIDsEmpty:
    !Equals [ !Select [ 0, !Ref PostgresBYOSecurityGroupIDs ], "" ]

Resources:
  ArthurRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsPostgresBYOSecurityGroupIDsEmpty
    Properties:
      GroupDescription: Arthur Postgres instance
      GroupName: !Sub "${ArthurResourceNamespace}-postgres${ArthurResourceNameSuffix}"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VPCCidrBlock
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  ArthurRDSSecurityGroupsOutput:
    Description: Security groups allowing for the Arthur RDS instances
    Value: !If
      - IsPostgresBYOSecurityGroupIDsEmpty
      - !Ref ArthurRDSSecurityGroup
      - !Join [ ",", !Ref PostgresBYOSecurityGroupIDs ]
