AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ArthurResourceNamespace:
    Description: 'A unique namespace for this Arthur stack resources (e.g. arthur1). It should be between 1 and 14 characters long.'
    Type: String
    MinLength: '1'
    MaxLength: '14'
    ConstraintDescription: 'The Arthur platform resources namespace must be 1-14 characters long.'
    Default: 'arthur'
  ArthurResourceNameSuffix:
    Description: 'Name suffix for this Arthur stack resources (e.g. -prod). It should be between 0 and 5 characters long.'
    Type: String
    MinLength: '0'
    MaxLength: '5'
    ConstraintDescription: 'The Arthur platform resources name suffix must be 0-5 characters long.'
    Default: ''
  OpenAIEmbeddingModelNamesEndpointsAndKeys:
    Description: "Connection strings for OpenAI GPT model endpoints. Must be in form \"DEPLOYMENT_NAME1::OPENAI_ENDPOINT1::SECRET_KEY1,DEPLOYMENT_NAME2::OPENAI_ENDPOINT2::SECRET_KEY2\"). The endpoint URLs must end with '/'. Many may be specified."
    Type: String
    NoEcho: true
    Default: 'none'
  OpenAIGPTModelNamesEndpointsAndKeys:
    Description: "Connection strings for OpenAI text-embedding-ada-002 embedding model endpoints. Must be in form \"DEPLOYMENT_NAME1::OPENAI_ENDPOINT1::SECRET_KEY1,DEPLOYMENT_NAME2::OPENAI_ENDPOINT2::SECRET_KEY2\"). The URLs must end with '/'. Many may be specified. Leave blank if Chat is disabled."
    Type: String
    NoEcho: true
Conditions:
  IsOpenAIEmbeddingModelNamesEndpointsAndKeysEmpty: !Equals [ !Ref OpenAIEmbeddingModelNamesEndpointsAndKeys, '' ]
Resources:
  GenaiEngineOpenAIEmbeddingModelNamesEndpointsAndKeysSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${ArthurResourceNamespace}_genai_engine_openai_embedding_model_names_endpoints_and_keys${ArthurResourceNameSuffix}"
      SecretString: !If [ IsOpenAIEmbeddingModelNamesEndpointsAndKeysEmpty, 'none', !Ref OpenAIEmbeddingModelNamesEndpointsAndKeys ]
  GenaiEngineOpenAIGPTModelNamesEndpointsAndKeysSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${ArthurResourceNamespace}_genai_engine_openai_gpt_model_names_endpoints_and_keys${ArthurResourceNameSuffix}"
      SecretString: !Ref OpenAIGPTModelNamesEndpointsAndKeys
  GenaiEngineAppKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${ArthurResourceNamespace}_genai_engine_app_key_secret${ArthurResourceNameSuffix}"
      GenerateSecretString:
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 32
  GenaiEngineAuthClientSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${ArthurResourceNamespace}_genai_engine_auth_client_secret${ArthurResourceNameSuffix}"
      GenerateSecretString:
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 32
  GenaiEngineAPIKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "${ArthurResourceNamespace}_genai_engine_admin_key_secret${ArthurResourceNameSuffix}"
      GenerateSecretString:
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 32
Outputs:
  GenaiEngineOpenAIEmbeddingModelNamesEndpointsAndKeysSecretOutput:
    Description: 'Secret containing OpenAI embedding model connection strings'
    Value: !Ref GenaiEngineOpenAIEmbeddingModelNamesEndpointsAndKeysSecret
  GenaiEngineOpenAIGPTModelNamesEndpointsAndKeysSecretOutput:
    Description: 'Secret containing OpenAI GPT model connection strings'
    Value: !Ref GenaiEngineOpenAIGPTModelNamesEndpointsAndKeysSecret
  GenaiEngineAppKeySecretOutput:
    Description: 'Client secret used for GenAI Engine to interface with Auth'
    Value: !Ref GenaiEngineAppKeySecret
  GenaiEngineAuthClientSecretOutput:
    Description: 'Secret key used for synchronizing tokens between services'
    Value: !Ref GenaiEngineAuthClientSecret
  GenaiEngineAPIKeySecretOutput:
    Description: 'Master API key for GenAI Engine services'
    Value: !Ref GenaiEngineAPIKeySecret
