#!/usr/bin/env python3
"""Render a human-readable Markdown vulnerability-justification report from a Trivy JSON report.

This is the customer-facing "justification doc": it lists every HIGH/CRITICAL finding in an
image, whether a fix is available, and — for findings suppressed by our VEX source of truth
(security/vex/) — the documented status and justification.

Stdlib only (runs on any Python 3.x available on the CI runner).

Usage:
    python3 security/render_report.py <trivy_report.json> <output.md> [image_ref]

The Trivy report should be produced with, e.g.:
    trivy image --format json --severity HIGH,CRITICAL \
        --vex security/vex/openvex.json --show-suppressed \
        -o report.json <image_ref>
"""

import json
import sys


def _md_escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _vuln_row(v: dict) -> str:
    cve = v.get("VulnerabilityID", "")
    url = v.get("PrimaryURL", "")
    cve_cell = f"[{cve}]({url})" if url else cve
    fixed = v.get("FixedVersion") or "_no fix available_"
    return "| {cve} | {sev} | {pkg} | {installed} | {fixed} | {title} |".format(
        cve=cve_cell,
        sev=v.get("Severity", ""),
        pkg=_md_escape(v.get("PkgName", "")),
        installed=_md_escape(v.get("InstalledVersion", "")),
        fixed=_md_escape(fixed),
        title=_md_escape(v.get("Title", "") or v.get("Description", ""))[:120],
    )


def main() -> int:
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__ or "")
        return 2

    in_path, out_path = sys.argv[1], sys.argv[2]
    image_ref = sys.argv[3] if len(sys.argv) > 3 else None

    with open(in_path, encoding="utf-8") as fh:
        report = json.load(fh)

    image_ref = image_ref or report.get("ArtifactName", "unknown")
    results = report.get("Results") or []

    active = []  # (target, vuln) still affecting the image
    justified = []  # (target, modified_finding) suppressed via VEX / .trivyignore
    for result in results:
        target = result.get("Target", "")
        for v in result.get("Vulnerabilities") or []:
            active.append((target, v))
        # VEX/.trivyignore suppressions with --show-suppressed: Trivy ~0.56 used
        # "ModifiedFindings"; >=0.71 renames it to "ExperimentalModifiedFindings".
        for mf in (
            result.get("ExperimentalModifiedFindings")
            or result.get("ModifiedFindings")
            or []
        ):
            justified.append((target, mf))

    lines = []
    lines.append(f"# Vulnerability Justification Report — `{image_ref}`")
    lines.append("")
    lines.append(
        "Generated by Trivy with the Arthur VEX source of truth (`security/vex/`) applied. "
        "Severity scope: **HIGH, CRITICAL**.",
    )
    lines.append("")
    lines.append(
        f"**Summary:** {len(active)} unresolved finding(s) · "
        f"{len(justified)} justified/suppressed via VEX.",
    )
    lines.append("")

    lines.append("## Unresolved HIGH/CRITICAL findings")
    lines.append("")
    if active:
        lines.append(
            "These require remediation (upgrade the package/base image) or a new VEX statement.",
        )
        lines.append("")
        lines.append("| CVE | Severity | Package | Installed | Fixed | Title |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for _target, v in active:
            lines.append(_vuln_row(v))
    else:
        lines.append(
            "_None. No unresolved HIGH/CRITICAL vulnerabilities in this image._",
        )
    lines.append("")

    lines.append("## Justified / suppressed findings (VEX)")
    lines.append("")
    if justified:
        lines.append(
            "Documented as acceptable via `security/vex/`. Each carries a status and justification.",
        )
        lines.append("")
        lines.append(
            "| CVE | Severity | Package | Status | Justification / statement |",
        )
        lines.append("| --- | --- | --- | --- | --- |")
        for _target, mf in justified:
            finding = mf.get("Finding") or {}
            lines.append(
                "| {cve} | {sev} | {pkg} | {status} | {stmt} |".format(
                    cve=_md_escape(finding.get("VulnerabilityID", "")),
                    sev=_md_escape(finding.get("Severity", "")),
                    pkg=_md_escape(finding.get("PkgName", "")),
                    status=_md_escape(mf.get("Status", "")),
                    stmt=_md_escape(mf.get("Statement", "") or "")[:160],
                ),
            )
    else:
        lines.append(
            "_No VEX-suppressed findings (or this Trivy version does not emit `ModifiedFindings`)._",
        )
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Wrote {out_path}: {len(active)} unresolved, {len(justified)} justified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
