{{- if and (eq .Values.storageBackend "s3") .Values.awsCredentials.create (not .Values.serviceAccount.awsIrsaRoleArn) (not .Values.serviceAccountAWSIrsaRoleArn) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arthur-model-upload.fullname" . }}{{ if or .Values.arthurResourceNameSuffix .Values.resourceNameSuffix }}-{{ .Values.arthurResourceNameSuffix | default .Values.resourceNameSuffix }}{{ end }}-aws-credentials
  labels:
    {{- include "arthur-model-upload.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | b64enc }}
  {{- if .Values.awsCredentials.region }}
  AWS_REGION: {{ .Values.awsCredentials.region | b64enc }}
  {{- end }}
{{- end }}
