{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arthur-model-upload.serviceAccountName" . }}{{ if or .Values.arthurResourceNameSuffix .Values.resourceNameSuffix }}-{{ .Values.arthurResourceNameSuffix | default .Values.resourceNameSuffix }}{{ end }}
  labels:
    {{- include "arthur-model-upload.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if or .Values.serviceAccount.awsIrsaRoleArn .Values.serviceAccountAWSIrsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsIrsaRoleArn | default .Values.serviceAccountAWSIrsaRoleArn | quote }}
    {{- end }}
    {{- if .Values.serviceAccount.gcpWorkloadIdentityEmail }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpWorkloadIdentityEmail | quote }}
    {{- end }}
{{- end }}
