
name: arthur-ml-engine
services:
  ml-engine:
    container_name: arthur-ml-engine
    image: arthurplatform/ml-engine:${ML_ENGINE_VERSION-latest}
    platform: linux/amd64
    restart: unless-stopped
    stop_grace_period: "60s"
    env_file:
      - .env
    entrypoint: [ "bash", "-c", "until wget --spider --quiet http://host.docker.internal:3030/docs; do sleep 1; done; python3 app/job_agent.py" ]
    healthcheck:
      test: wget -qO - http://127.0.0.1:7492/health
      interval: 30s
      timeout: 5s
      retries: 5
