/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatDocumentContext } from './chat-document-context';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalRuleResult } from './external-rule-result';

/**
 * 
 * @export
 * @interface ChatResponse
 */
export interface ChatResponse {
    /**
     * ID of the inference sent to the chat
     * @type {string}
     * @memberof ChatResponse
     */
    'inference_id': string;
    /**
     * ID of the conversation session
     * @type {string}
     * @memberof ChatResponse
     */
    'conversation_id': string;
    /**
     * Time the inference was made in unix milliseconds
     * @type {number}
     * @memberof ChatResponse
     */
    'timestamp': number;
    /**
     * related sections of documents that were most relevant to the inference prompt. Formatted as a list of retrieved context chunks which include document name, seq num, and context.
     * @type {Array<ChatDocumentContext>}
     * @memberof ChatResponse
     */
    'retrieved_context': Array<ChatDocumentContext>;
    /**
     * response from the LLM for the original user prompt
     * @type {string}
     * @memberof ChatResponse
     */
    'llm_response': string;
    /**
     * list of rule results for the user prompt
     * @type {Array<ExternalRuleResult>}
     * @memberof ChatResponse
     */
    'prompt_results': Array<ExternalRuleResult>;
    /**
     * list of rule results for the llm response
     * @type {Array<ExternalRuleResult>}
     * @memberof ChatResponse
     */
    'response_results': Array<ExternalRuleResult>;
}

