/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BaseDetailsResponse } from './base-details-response';
// May contain unused imports in some cases
// @ts-ignore
import type { HallucinationClaimResponse } from './hallucination-claim-response';
// May contain unused imports in some cases
// @ts-ignore
import type { HallucinationDetailsResponse } from './hallucination-details-response';
// May contain unused imports in some cases
// @ts-ignore
import type { KeywordDetailsResponse } from './keyword-details-response';
// May contain unused imports in some cases
// @ts-ignore
import type { KeywordSpanResponse } from './keyword-span-response';
// May contain unused imports in some cases
// @ts-ignore
import type { PIIDetailsResponse } from './piidetails-response';
// May contain unused imports in some cases
// @ts-ignore
import type { PIIEntitySpanResponse } from './piientity-span-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RegexDetailsResponse } from './regex-details-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RegexSpanResponse } from './regex-span-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ToxicityDetailsResponse } from './toxicity-details-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ToxicityViolationType } from './toxicity-violation-type';

/**
 * Details of the rule output
 * @export
 * @interface Details
 */
export interface Details {
    /**
     * 
     * @type {Array<HallucinationClaimResponse>}
     * @memberof Details
     */
    'claims': Array<HallucinationClaimResponse>;
    /**
     * 
     * @type {Array<PIIEntitySpanResponse>}
     * @memberof Details
     */
    'pii_entities': Array<PIIEntitySpanResponse>;
    /**
     * 
     * @type {ToxicityViolationType}
     * @memberof Details
     */
    'toxicity_violation_type': ToxicityViolationType;
    /**
     * 
     * @type {boolean}
     * @memberof Details
     */
    'score'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Details
     */
    'message'?: string;
    /**
     * Each keyword in this list corresponds to a keyword that was both configured in the rule that was run and found in the input text.
     * @type {Array<KeywordSpanResponse>}
     * @memberof Details
     */
    'keyword_matches'?: Array<KeywordSpanResponse>;
    /**
     * Each string in this list corresponds to a matching span from the input text that matches the configured regex rule.
     * @type {Array<RegexSpanResponse>}
     * @memberof Details
     */
    'regex_matches'?: Array<RegexSpanResponse>;
    /**
     * 
     * @type {number}
     * @memberof Details
     */
    'toxicity_score'?: number;
}



