/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExternalInferencePrompt } from './external-inference-prompt';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalInferenceResponse } from './external-inference-response';
// May contain unused imports in some cases
// @ts-ignore
import type { InferenceFeedbackResponse } from './inference-feedback-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleResultEnum } from './rule-result-enum';

/**
 * 
 * @export
 * @interface ExternalInference
 */
export interface ExternalInference {
    /**
     * 
     * @type {string}
     * @memberof ExternalInference
     */
    'id': string;
    /**
     * 
     * @type {RuleResultEnum}
     * @memberof ExternalInference
     */
    'result': RuleResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ExternalInference
     */
    'created_at': number;
    /**
     * 
     * @type {number}
     * @memberof ExternalInference
     */
    'updated_at': number;
    /**
     * 
     * @type {ExternalInferencePrompt}
     * @memberof ExternalInference
     */
    'inference_prompt': ExternalInferencePrompt;
    /**
     * 
     * @type {Array<InferenceFeedbackResponse>}
     * @memberof ExternalInference
     */
    'inference_feedback': Array<InferenceFeedbackResponse>;
    /**
     * 
     * @type {string}
     * @memberof ExternalInference
     */
    'task_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalInference
     */
    'task_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalInference
     */
    'conversation_id'?: string | null;
    /**
     * 
     * @type {ExternalInferenceResponse}
     * @memberof ExternalInference
     */
    'inference_response'?: ExternalInferenceResponse | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalInference
     */
    'user_id'?: string | null;
}



