/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExternalRuleResult } from './external-rule-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleResultEnum } from './rule-result-enum';

/**
 * 
 * @export
 * @interface ExternalInferenceResponse
 */
export interface ExternalInferenceResponse {
    /**
     * 
     * @type {string}
     * @memberof ExternalInferenceResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ExternalInferenceResponse
     */
    'inference_id': string;
    /**
     * 
     * @type {RuleResultEnum}
     * @memberof ExternalInferenceResponse
     */
    'result': RuleResultEnum;
    /**
     * 
     * @type {number}
     * @memberof ExternalInferenceResponse
     */
    'created_at': number;
    /**
     * 
     * @type {number}
     * @memberof ExternalInferenceResponse
     */
    'updated_at': number;
    /**
     * 
     * @type {string}
     * @memberof ExternalInferenceResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<ExternalRuleResult>}
     * @memberof ExternalInferenceResponse
     */
    'response_rule_results': Array<ExternalRuleResult>;
    /**
     * 
     * @type {string}
     * @memberof ExternalInferenceResponse
     */
    'context'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ExternalInferenceResponse
     */
    'tokens'?: number | null;
}



