/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HallucinationClaimResponse } from './hallucination-claim-response';

/**
 * 
 * @export
 * @interface HallucinationDetailsResponse
 */
export interface HallucinationDetailsResponse {
    /**
     * 
     * @type {Array<HallucinationClaimResponse>}
     * @memberof HallucinationDetailsResponse
     */
    'claims': Array<HallucinationClaimResponse>;
    /**
     * 
     * @type {boolean}
     * @memberof HallucinationDetailsResponse
     */
    'score'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof HallucinationDetailsResponse
     */
    'message'?: string | null;
}

