/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InferenceFeedbackTarget } from './inference-feedback-target';

/**
 * 
 * @export
 * @interface InferenceFeedbackResponse
 */
export interface InferenceFeedbackResponse {
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'inference_id': string;
    /**
     * 
     * @type {InferenceFeedbackTarget}
     * @memberof InferenceFeedbackResponse
     */
    'target': InferenceFeedbackTarget;
    /**
     * 
     * @type {number}
     * @memberof InferenceFeedbackResponse
     */
    'score': number;
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'reason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InferenceFeedbackResponse
     */
    'user_id'?: string | null;
}



