/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetricType } from './metric-type';

/**
 * 
 * @export
 * @interface MetricResponse
 */
export interface MetricResponse {
    /**
     * ID of the Metric
     * @type {string}
     * @memberof MetricResponse
     */
    'id': string;
    /**
     * Name of the Metric
     * @type {string}
     * @memberof MetricResponse
     */
    'name': string;
    /**
     * Type of the Metric
     * @type {MetricType}
     * @memberof MetricResponse
     */
    'type': MetricType;
    /**
     * Metadata of the Metric
     * @type {string}
     * @memberof MetricResponse
     */
    'metric_metadata': string;
    /**
     * Time the Metric was created in unix milliseconds
     * @type {string}
     * @memberof MetricResponse
     */
    'created_at': string;
    /**
     * Time the Metric was updated in unix milliseconds
     * @type {string}
     * @memberof MetricResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {string}
     * @memberof MetricResponse
     */
    'config'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MetricResponse
     */
    'enabled'?: boolean | null;
}



