/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetricResultResponse } from './metric-result-response';

/**
 * Nested span response with children for building span trees
 * @export
 * @interface NestedSpanWithMetricsResponse
 */
export interface NestedSpanWithMetricsResponse {
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'trace_id': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'span_id': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'start_time': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'end_time': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {object}
     * @memberof NestedSpanWithMetricsResponse
     */
    'raw_data': object;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'parent_span_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'span_kind'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'span_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'task_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'system_prompt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'user_query'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedSpanWithMetricsResponse
     */
    'response'?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof NestedSpanWithMetricsResponse
     */
    'context'?: Array<object> | null;
    /**
     * List of metric results for this span
     * @type {Array<MetricResultResponse>}
     * @memberof NestedSpanWithMetricsResponse
     */
    'metric_results'?: Array<MetricResultResponse>;
    /**
     * Child spans nested under this span
     * @type {Array<NestedSpanWithMetricsResponse>}
     * @memberof NestedSpanWithMetricsResponse
     */
    'children'?: Array<NestedSpanWithMetricsResponse>;
}

