/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetricType } from './metric-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RelevanceMetricConfig } from './relevance-metric-config';

/**
 * 
 * @export
 * @interface NewMetricRequest
 */
export interface NewMetricRequest {
    /**
     * Type of the metric. It can only be one of QueryRelevance, ResponseRelevance, ToolSelection
     * @type {MetricType}
     * @memberof NewMetricRequest
     */
    'type': MetricType;
    /**
     * Name of metric
     * @type {string}
     * @memberof NewMetricRequest
     */
    'name': string;
    /**
     * Additional metadata for the metric
     * @type {string}
     * @memberof NewMetricRequest
     */
    'metric_metadata': string;
    /**
     * 
     * @type {RelevanceMetricConfig}
     * @memberof NewMetricRequest
     */
    'config'?: RelevanceMetricConfig | null;
}



