/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewTaskRequest
 */
export interface NewTaskRequest {
    /**
     * Name of the task.
     * @type {string}
     * @memberof NewTaskRequest
     */
    'name': string;
    /**
     * Whether the task is agentic or not.
     * @type {boolean}
     * @memberof NewTaskRequest
     */
    'is_agentic'?: boolean;
}

