/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Config } from './config';

/**
 * 
 * @export
 * @interface NewRuleRequest
 */
export interface NewRuleRequest {
    /**
     * Name of the rule
     * @type {string}
     * @memberof NewRuleRequest
     */
    'name': string;
    /**
     * Type of the rule. It can only be one of KeywordRule, RegexRule, ModelSensitiveDataRule, ModelHallucinationRule, ModelHallucinationRuleV2, PromptInjectionRule, PIIDataRule
     * @type {string}
     * @memberof NewRuleRequest
     */
    'type': string;
    /**
     * Boolean value to enable or disable the rule for llm prompt
     * @type {boolean}
     * @memberof NewRuleRequest
     */
    'apply_to_prompt': boolean;
    /**
     * Boolean value to enable or disable the rule for llm response
     * @type {boolean}
     * @memberof NewRuleRequest
     */
    'apply_to_response': boolean;
    /**
     * 
     * @type {Config}
     * @memberof NewRuleRequest
     */
    'config'?: Config | null;
}

