/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PIIEntityTypes } from './piientity-types';

/**
 * 
 * @export
 * @interface PIIEntitySpanResponse
 */
export interface PIIEntitySpanResponse {
    /**
     * 
     * @type {PIIEntityTypes}
     * @memberof PIIEntitySpanResponse
     */
    'entity': PIIEntityTypes;
    /**
     * The subtext within the input string that was identified as PII.
     * @type {string}
     * @memberof PIIEntitySpanResponse
     */
    'span': string;
    /**
     * 
     * @type {number}
     * @memberof PIIEntitySpanResponse
     */
    'confidence'?: number | null;
}



