/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PromptValidationRequest
 */
export interface PromptValidationRequest {
    /**
     * Prompt to be validated by GenAI Engine
     * @type {string}
     * @memberof PromptValidationRequest
     */
    'prompt': string;
    /**
     * 
     * @type {string}
     * @memberof PromptValidationRequest
     */
    'conversation_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PromptValidationRequest
     */
    'user_id'?: string | null;
}

