/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InferenceFeedbackResponse } from './inference-feedback-response';

/**
 * 
 * @export
 * @interface QueryFeedbackResponse
 */
export interface QueryFeedbackResponse {
    /**
     * List of inferences matching the search filters. Length is less than or equal to page_size parameter
     * @type {Array<InferenceFeedbackResponse>}
     * @memberof QueryFeedbackResponse
     */
    'feedback': Array<InferenceFeedbackResponse>;
    /**
     * The current page number
     * @type {number}
     * @memberof QueryFeedbackResponse
     */
    'page': number;
    /**
     * The number of feedback items per page
     * @type {number}
     * @memberof QueryFeedbackResponse
     */
    'page_size': number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof QueryFeedbackResponse
     */
    'total_pages': number;
    /**
     * The total number of feedback items matching the query parameters
     * @type {number}
     * @memberof QueryFeedbackResponse
     */
    'total_count': number;
}

