/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpanWithMetricsResponse } from './span-with-metrics-response';

/**
 * 
 * @export
 * @interface QuerySpansResponse
 */
export interface QuerySpansResponse {
    /**
     * The total number of spans matching the query parameters
     * @type {number}
     * @memberof QuerySpansResponse
     */
    'count': number;
    /**
     * List of spans with metrics matching the search filters
     * @type {Array<SpanWithMetricsResponse>}
     * @memberof QuerySpansResponse
     */
    'spans': Array<SpanWithMetricsResponse>;
}

