/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TraceResponse } from './trace-response';

/**
 * New response format that groups spans into traces with nested structure
 * @export
 * @interface QueryTracesWithMetricsResponse
 */
export interface QueryTracesWithMetricsResponse {
    /**
     * The total number of spans matching the query parameters
     * @type {number}
     * @memberof QueryTracesWithMetricsResponse
     */
    'count': number;
    /**
     * List of traces containing nested spans matching the search filters
     * @type {Array<TraceResponse>}
     * @memberof QueryTracesWithMetricsResponse
     */
    'traces': Array<TraceResponse>;
}

