/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Configuration for relevance metrics including QueryRelevance and ResponseRelevance
 * @export
 * @interface RelevanceMetricConfig
 */
export interface RelevanceMetricConfig {
    /**
     * 
     * @type {number}
     * @memberof RelevanceMetricConfig
     */
    'relevance_threshold'?: number | null;
    /**
     * Whether to use LLM as a judge for relevance scoring
     * @type {boolean}
     * @memberof RelevanceMetricConfig
     */
    'use_llm_judge'?: boolean;
}

