/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Config1 } from './config1';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleScope } from './rule-scope';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleType } from './rule-type';

/**
 * 
 * @export
 * @interface RuleResponse
 */
export interface RuleResponse {
    /**
     * ID of the Rule
     * @type {string}
     * @memberof RuleResponse
     */
    'id': string;
    /**
     * Name of the Rule
     * @type {string}
     * @memberof RuleResponse
     */
    'name': string;
    /**
     * Type of Rule
     * @type {RuleType}
     * @memberof RuleResponse
     */
    'type': RuleType;
    /**
     * Rule applies to prompt
     * @type {boolean}
     * @memberof RuleResponse
     */
    'apply_to_prompt': boolean;
    /**
     * Rule applies to response
     * @type {boolean}
     * @memberof RuleResponse
     */
    'apply_to_response': boolean;
    /**
     * Scope of the rule. The rule can be set at default level or task level.
     * @type {RuleScope}
     * @memberof RuleResponse
     */
    'scope': RuleScope;
    /**
     * Time the rule was created in unix milliseconds
     * @type {number}
     * @memberof RuleResponse
     */
    'created_at': number;
    /**
     * Time the rule was updated in unix milliseconds
     * @type {number}
     * @memberof RuleResponse
     */
    'updated_at': number;
    /**
     * 
     * @type {boolean}
     * @memberof RuleResponse
     */
    'enabled'?: boolean | null;
    /**
     * 
     * @type {Config1}
     * @memberof RuleResponse
     */
    'config'?: Config1 | null;
}



