/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RuleScope } from './rule-scope';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleType } from './rule-type';

/**
 * 
 * @export
 * @interface SearchRulesRequest
 */
export interface SearchRulesRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchRulesRequest
     */
    'rule_ids'?: Array<string> | null;
    /**
     * 
     * @type {Array<RuleScope>}
     * @memberof SearchRulesRequest
     */
    'rule_scopes'?: Array<RuleScope> | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchRulesRequest
     */
    'prompt_enabled'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SearchRulesRequest
     */
    'response_enabled'?: boolean | null;
    /**
     * 
     * @type {Array<RuleType>}
     * @memberof SearchRulesRequest
     */
    'rule_types'?: Array<RuleType> | null;
}

