/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MetricResponse } from './metric-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RuleResponse } from './rule-response';

/**
 * 
 * @export
 * @interface TaskResponse
 */
export interface TaskResponse {
    /**
     *  ID of the task
     * @type {string}
     * @memberof TaskResponse
     */
    'id': string;
    /**
     * Name of the task
     * @type {string}
     * @memberof TaskResponse
     */
    'name': string;
    /**
     * Time the task was created in unix milliseconds
     * @type {number}
     * @memberof TaskResponse
     */
    'created_at': number;
    /**
     * Time the task was created in unix milliseconds
     * @type {number}
     * @memberof TaskResponse
     */
    'updated_at': number;
    /**
     * List of all the rules for the task.
     * @type {Array<RuleResponse>}
     * @memberof TaskResponse
     */
    'rules': Array<RuleResponse>;
    /**
     * 
     * @type {boolean}
     * @memberof TaskResponse
     */
    'is_agentic'?: boolean | null;
    /**
     * 
     * @type {Array<MetricResponse>}
     * @memberof TaskResponse
     */
    'metrics'?: Array<MetricResponse> | null;
}

