/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthUserRole } from './auth-user-role';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'email': string;
    /**
     * 
     * @type {Array<AuthUserRole>}
     * @memberof UserResponse
     */
    'roles': Array<AuthUserRole>;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'first_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'last_name'?: string | null;
}

