"""Add relationship between inferences and tasks table.

Revision ID: e00e4d87eea5
Revises: 5ccb9c8c9a77
Create Date: 2024-07-01 17:08:40.728677

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e00e4d87eea5"
down_revision = "5ccb9c8c9a77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "inferences", "tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "inferences", type_="foreignkey")
    # ### end Alembic commands ###
