"""add trace end time index

Revision ID: 711e7d7236ae
Revises: 04c5e8528072
Create Date: 2026-04-07 12:57:16.481379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711e7d7236ae'
down_revision = '04c5e8528072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_traces_end_time', 'trace_metadata', ['end_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_traces_end_time', table_name='trace_metadata')
    # ### end Alembic commands ###
