"""create_service_name_map

Revision ID: c2b62e95341f
Revises: 516d579bd164
Create Date: 2026-02-06 12:46:01.575248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b62e95341f'
down_revision = '516d579bd164'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_name_task_mappings',
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_name')
    )
    op.create_index('idx_service_name_mapping_task', 'service_name_task_mappings', ['service_name', 'task_id'], unique=False)
    op.create_index(op.f('ix_service_name_task_mappings_task_id'), 'service_name_task_mappings', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_name_task_mappings_task_id'), table_name='service_name_task_mappings')
    op.drop_index('idx_service_name_mapping_task', table_name='service_name_task_mappings')
    op.drop_table('service_name_task_mappings')
    # ### end Alembic commands ###
