"""add annotations index

Revision ID: a8e90125e931
Revises: c2ef79d7a62d
Create Date: 2026-02-03 14:59:43.826707

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8e90125e931"
down_revision = "c2ef79d7a62d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_agentic_annotations_continuous_eval_created",
        "agentic_annotations",
        ["continuous_eval_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_agentic_annotations_continuous_eval_created",
        table_name="agentic_annotations",
    )
    # ### end Alembic commands ###
