"""add agentic polling table

Revision ID: 6bb9c3509892
Revises: 4af384f67b6b
Create Date: 2026-02-05 12:13:33.654617

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6bb9c3509892"
down_revision = "4af384f67b6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_polling_data",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column(
            "gcp_credentials",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("failed_runs", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("last_fetched", sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint(
            "provider != 'gcp' OR (\n                gcp_credentials ? 'project_id' AND\n                gcp_credentials ? 'region' AND\n                gcp_credentials ? 'resource_id' AND\n                gcp_credentials->>'project_id' IS NOT NULL AND\n                gcp_credentials->>'region' IS NOT NULL AND\n                gcp_credentials->>'resource_id' IS NOT NULL\n            )",
            name="ck_gcp_credentials_fields",
        ),
        sa.CheckConstraint(
            "provider != 'gcp' OR gcp_credentials IS NOT NULL",
            name="ck_gcp_credentials_required",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_polling_data_created_at"),
        "agent_polling_data",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_polling_data_task_id"),
        "agent_polling_data",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_polling_data_updated_at"),
        "agent_polling_data",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "uq_gcp_resource_id",
        "agent_polling_data",
        [sa.literal_column("(gcp_credentials->>'resource_id')")],
        unique=True,
        postgresql_where=sa.text(
            "provider = 'gcp' AND gcp_credentials->>'resource_id' IS NOT NULL",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_gcp_resource_id",
        table_name="agent_polling_data",
        postgresql_where=sa.text(
            "provider = 'gcp' AND gcp_credentials->>'resource_id' IS NOT NULL",
        ),
    )
    op.drop_index(
        op.f("ix_agent_polling_data_updated_at"),
        table_name="agent_polling_data",
    )
    op.drop_index(
        op.f("ix_agent_polling_data_task_id"),
        table_name="agent_polling_data",
    )
    op.drop_index(
        op.f("ix_agent_polling_data_created_at"),
        table_name="agent_polling_data",
    )
    op.drop_table("agent_polling_data")
    # ### end Alembic commands ###
