/* tslint:disable */
/* eslint-disable */
/**
 * Arthur GenAI Engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.1.79
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * TracesApi - axios parameter creator
 * @export
 */
export const TracesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Receiver for OpenInference trace standard.
         * @summary Receive Traces
         * @param {File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveTracesV1TracesPost: async (body: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('receiveTracesV1TracesPost', 'body', body)
            const localVarPath = `/v1/traces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication API Key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TracesApi - functional programming interface
 * @export
 */
export const TracesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TracesApiAxiosParamCreator(configuration)
    return {
        /**
         * Receiver for OpenInference trace standard.
         * @summary Receive Traces
         * @param {File} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiveTracesV1TracesPost(body: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiveTracesV1TracesPost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TracesApi.receiveTracesV1TracesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TracesApi - factory interface
 * @export
 */
export const TracesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TracesApiFp(configuration)
    return {
        /**
         * Receiver for OpenInference trace standard.
         * @summary Receive Traces
         * @param {TracesApiReceiveTracesV1TracesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveTracesV1TracesPost(requestParameters: TracesApiReceiveTracesV1TracesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.receiveTracesV1TracesPost(requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TracesApi - interface
 * @export
 * @interface TracesApi
 */
export interface TracesApiInterface {
    /**
     * Receiver for OpenInference trace standard.
     * @summary Receive Traces
     * @param {TracesApiReceiveTracesV1TracesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TracesApiInterface
     */
    receiveTracesV1TracesPost(requestParameters: TracesApiReceiveTracesV1TracesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * Request parameters for receiveTracesV1TracesPost operation in TracesApi.
 * @export
 * @interface TracesApiReceiveTracesV1TracesPostRequest
 */
export interface TracesApiReceiveTracesV1TracesPostRequest {
    /**
     * 
     * @type {File}
     * @memberof TracesApiReceiveTracesV1TracesPost
     */
    readonly body: File
}

/**
 * TracesApi - object-oriented interface
 * @export
 * @class TracesApi
 * @extends {BaseAPI}
 */
export class TracesApi extends BaseAPI implements TracesApiInterface {
    /**
     * Receiver for OpenInference trace standard.
     * @summary Receive Traces
     * @param {TracesApiReceiveTracesV1TracesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TracesApi
     */
    public receiveTracesV1TracesPost(requestParameters: TracesApiReceiveTracesV1TracesPostRequest, options?: RawAxiosRequestConfig) {
        return TracesApiFp(this.configuration).receiveTracesV1TracesPost(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

