AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ArthurResourceNamespace:
    Description: 'A unique namespace for this Arthur stack resources (e.g. arthur1). It should be between 1 and 14 characters long.'
    Type: String
    MinLength: '1'
    MaxLength: '14'
    ConstraintDescription: 'The Arthur platform resources namespace must be 1-14 characters long.'
    Default: 'arthur'
  ArthurResourceNameSuffix:
    Description: 'Name suffix for this Arthur stack resources (e.g. -prod). It should be between 0 and 5 characters long.'
    Type: String
    MinLength: '0'
    MaxLength: '5'
    ConstraintDescription: 'The Arthur platform resources name suffix must be 0-5 characters long.'
    Default: ''
Resources:
  ArthurECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ArthurResourceNamespace}${ArthurResourceNameSuffix}"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
Outputs:
  ArthurECSClusterNameOutput:
    Description: 'ECS cluster name for Arthur'
    Value: !Ref ArthurECSCluster
