AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ArthurResourceNamespace:
    Description: 'A unique namespace for this Arthur stack resources (e.g. arthur1). It should be between 1 and 14 characters long.'
    Type: String
    MinLength: '1'
    MaxLength: '14'
    ConstraintDescription: 'The Arthur platform resources namespace must be 1-14 characters long.'
    Default: 'arthur'
  ArthurResourceNameSuffix:
    Description: 'Name suffix for this Arthur stack resources (e.g. -prod). It should be between 0 and 5 characters long.'
    Type: String
    MinLength: '0'
    MaxLength: '5'
    ConstraintDescription: 'The Arthur platform resources name suffix must be 0-5 characters long.'
    Default: ''
  AlarmSNSTopicArn:
    Type: String
    Description: 'The ARN of the SNS topic to send the alarms to'
  ArthurECSClusterName:
    Type: String
    Default: 'arthur'
    Description: 'The Arthur ECS cluster name (e.g. arthur)'
  MLEngineECSServiceName:
    Type: String
    Default: 'arthur-ml-engine'
    Description: 'The Arthur ML Engine ECS service name (e.g. arthur-ml-engine)'
  MLEngineECSMemoryAlarmThreshold:
    Type: Number
    Default: 80
    Description: 'Alarm is triggered when Arthur ML Engine service uses this percentage of memory in a minute'
  MLEngineECSCPUAlarmThreshold:
    Type: Number
    Default: 80
    Description: 'Alarm is triggered when Arthur ML Engine service uses this percentage of CPU in a minute'

Resources:
  ArthurMLEngineECSMemory:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "[${ArthurResourceNamespace}${ArthurResourceNameSuffix}] ml-engine-ecs-memory-alarm"
      AlarmDescription: !Sub "Alarm when Arthur ML Engine service uses max ${MLEngineECSMemoryAlarmThreshold}% of memory in a minute"
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Maximum
      Dimensions:
        - Name: ServiceName
          Value: !Ref MLEngineECSServiceName
        - Name: ClusterName
          Value: !Ref ArthurECSClusterName
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: !Ref MLEngineECSMemoryAlarmThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold

  ArthurMLEngineECSCPU:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "[${ArthurResourceNamespace}${ArthurResourceNameSuffix}] ml-engine-ecs-cpu-alarm"
      AlarmDescription: !Sub "Alarm when Arthur ML Engine service uses max ${MLEngineECSCPUAlarmThreshold}% of CPU in a minute"
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Maximum
      Dimensions:
        - Name: ServiceName
          Value: !Ref MLEngineECSServiceName
        - Name: ClusterName
          Value: !Ref ArthurECSClusterName
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: !Ref MLEngineECSCPUAlarmThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
