AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ArthurResourceNamespace:
    Description: 'A unique namespace for this Arthur stack resources (e.g. arthur1). It should be between 1 and 14 characters long.'
    Type: String
    MinLength: '1'
    MaxLength: '14'
    ConstraintDescription: 'The Arthur platform resources namespace must be 1-14 characters long.'
    Default: 'arthur'
  ArthurResourceNameSuffix:
    Description: '(Optional) Name suffix for this Arthur stack resources (e.g. -prod). It should be between 0 and 5 characters long.'
    Type: String
    MinLength: '0'
    MaxLength: '5'
    ConstraintDescription: 'The Arthur platform resources name suffix must be 0-5 characters long.'
    Default: ''
  MLEngineContainerImageLocation:
    Description: 'The container image location for Arthur ML Engine'
    Type: String
    AllowedPattern: '.+'
    Default: 'arthurplatform/ml-engine'
    ConstraintDescription: 'The container image location for Arthur ML Engine must be specified.'
  ContainerRepositoryUsername:
    Description: '(Optional) Username for accessing the container repository'
    Type: String
    Default: ''
  ContainerRepositoryPassword:
    Description: '(Optional) Password for accessing the container repository'
    Type: String
    NoEcho: true
  ArthurApiHost:
    Description: 'Arthur API Host'
    Type: String
    AllowedPattern: '.+'
  MLEngineClientId:
    Description: 'Client ID for the ML Engine'
    Type: String
    AllowedPattern: '.+'
  MLEngineClientSecret:
    Description: 'Client Secret for the ML Engine'
    Type: String
    NoEcho: true
    AllowedPattern: '.+'
  MLEngineVersion:
    Description: 'Version tag for the ML Engine'
    Type: String
    Default: 'REPLACE_ME_ML_ENGINE_TAG'
    AllowedPattern: '.+'
    ConstraintDescription: 'ML Engine version must be specified.'
  AlarmSNSTopicArn:
    Description: 'The ARN of the SNS topic to send the CloudWatch alarms to'
    Type: String
    AllowedPattern: 'arn:aws:sns:.+'
    ConstraintDescription: 'A valid SNS ARN must be provided for the alarm SNS topic.'
  MLEngineECSMemoryAlarmThreshold:
    Type: Number
    Default: 80
    Description: 'Alarm is triggered when ML Engine service uses this percentage of memory in a minute'
  MLEngineECSCPUAlarmThreshold:
    Type: Number
    Default: 80
    Description: 'Alarm is triggered when ML Engine service uses this percentage of memory in a minute'
  ExistingArthurVPCId:
    Description: 'VPC to deploy Arthur stack to'
    Type: AWS::EC2::VPC::Id
    AllowedPattern: '.+'
    ConstraintDescription: 'VPC ID to deploy in must be defined'
  ExistingArthurVPCCidrBlock:
    Description: 'CIDR block of the Arthur stack VPC'
    Type: String
    AllowedPattern: '.+'
    ConstraintDescription: 'VPC CIDR block must be defined.'
  ArthurPrivateSubnets:
    Description: 'List of private subnets to use for the Arthur stack'
    Type: List<AWS::EC2::Subnet::Id>
    AllowedPattern: '.+'
    ConstraintDescription: 'Private subnets must be defined.'
  MLEngineBYOTaskRoleIAMArn:
    Type: String
    Description: '(Optional) IAM Role ARN to use for ML Engine ECS task role. If not specified, one will be provisioned.'
    AllowedPattern: '(arn:aws:iam:.+)?'
    ConstraintDescription: 'A valid ARN must be provided for the Arthur ML Engine task IAM role.'
  MLEngineBYOTaskExecutionRoleIAMArn:
    Type: String
    Description: '(Optional) IAM Role ARN to use for ML Engine ECS task execution role. If not specified, one will be provisioned.'
    AllowedPattern: '(arn:aws:iam:.+)?'
    ConstraintDescription: 'A valid ARN must be provided for the Arthur ML Engine task execution IAM role.'
  MLEngineBYOAppSecurityGroupIDs:
    Type: CommaDelimitedList
    Description: '(Optional) Security group ID to use for Arthur ML Engine application. If not specified, one will be provisioned.'
    Default: ''
    AllowedPattern: '^$|^sg-[0-9a-f]{8}(,sg-[0-9a-f]{8})*$|^sg-[0-9a-f]{17}(,sg-[0-9a-f]{17})*$'
    ConstraintDescription: 'Must be a comma-separated list of valid AWS security group IDs (sg- followed by 8 or 17 hexadecimal characters), or leave it empty.'
  MLEngineECSScaleCPUTargetValue:
    Type: Number
    Description: 'CPU target value for triggering ML Engine ECS service autoscaling'
    Default: 50
  MLEngineECSScaleMemoryTargetValue:
    Type: Number
    Description: 'CPU target value for triggering ML Engine ECS service autoscaling'
    Default: 25
  MLEngineECSScaleInCooldownInSecs:
    Type: Number
    Description: 'Scale-in cooldown time in seconds for ML Engine ECS autoscaling'
    Default: 300
  MLEngineECSScaleOutCooldownInSecs:
    Type: Number
    Description: 'Scale-out cooldown time in seconds for ML Engine ECS autoscaling'
    Default: 30
  MLEngineECSAutoscalingMaxCapacity:
    Type: Number
    Description: 'The maximum number of tasks allowed for ML Engine ECS service autoscaling'
    Default: 10
  MLEngineECSAutoscalingMinCapacity:
    Type: Number
    Description: 'The minimum number of tasks allowed for ML Engine ECS service autoscaling'
    Default: 2
  MLEngineECSServiceTaskDesiredCount:
    Type: Number
    Description: 'The desired number of tasks running for ML Engine ECS service'
    Default: 2
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Minimum Required Configurations'
        Parameters:
          - ArthurResourceNamespace
          - ExistingArthurVPCId
          - ExistingArthurVPCCidrBlock
          - ArthurPrivateSubnets
          - ArthurApiHost
          - MLEngineClientId
          - MLEngineClientSecret
      - Label:
          default: 'Advanced - General'
        Parameters:
          - ArthurResourceNameSuffix
          - ContainerRepositoryUsername
          - ContainerRepositoryPassword
      - Label:
          default: 'Advanced ML Engine (IAM)'
        Parameters:
          - MLEngineBYOTaskRoleIAMArn
          - MLEngineBYOTaskExecutionRoleIAMArn
    ParameterLabels:
      ContainerRepositoryUsername:
        default: 'Container Repository Username'
      ContainerRepositoryPassword:
        default: 'Container Repository Password'
      MLEngineBYOTaskRoleIAMArn:
        default: 'Bring-Your-Own ML Engine Task Role'
      MLEngineBYOTaskExecutionRoleIAMArn:
        default: 'Bring-Your-Own ML Engine Task Execution Role'
      ExistingArthurVPCId:
        default: 'Arthur Stack VPC ID'
      ExistingArthurVPCCidrBlock:
        default: 'Arthur Stack VPC CIDR Block'
      ArthurApiHost:
        default: 'Arthur API Host for the ML Engine to connect to'
      MLEngineClientId:
        default: 'Client ID for the ML Engine'
      MLEngineClientSecret:
        default: 'Client Secret for the ML Engine'
      ArthurPrivateSubnets:
        default: 'Arthur Stack Private Subnets'
Conditions:
  ContainerRepositoryCredentialRequired:
    !Not [ !Equals [ !Ref ContainerRepositoryUsername, '' ] ]
Resources:
  CoreVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExistingVPCId: !Ref ExistingArthurVPCId
        ExistingVPCCidrBlock: !Ref ExistingArthurVPCCidrBlock
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-core-vpc.yml"
  CoreSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        VPCId: !GetAtt [ CoreVPCStack, Outputs.VPCIdOutput ]
        VPCCidrBlock: !GetAtt [ CoreVPCStack, Outputs.VPCCidrBlockOutput ]
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-core-security-groups.yml"
  CoreSecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        ContainerRepositoryUsername: !Ref ContainerRepositoryUsername
        ContainerRepositoryPassword: !Ref ContainerRepositoryPassword
        CreatePostgresSecret: 'false'
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-core-secrets-manager.yml"
  CoreECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-core-ecs.yml"
  MLEngineSecretsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        MLEngineClientId: !Ref MLEngineClientId
        MLEngineClientSecret: !Ref MLEngineClientSecret
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-secrets-manager.yml"
  MLEngineIAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        MLEngineBYOTaskRoleIAMArn: !Ref MLEngineBYOTaskRoleIAMArn
        MLEngineBYOTaskExecutionRoleIAMArn: !Ref MLEngineBYOTaskExecutionRoleIAMArn
        MLEngineSecretArns: !Join
          - ','
          - - !GetAtt [ CoreSecretsStack, Outputs.ContainerRepositoryCredentialsSecretOutput ]
            - !GetAtt [ MLEngineSecretsStack, Outputs.MLEngineClientCredentialsSecretOutput ]
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-iam.yml"
  MLEngineSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        VPCId: !GetAtt [ CoreVPCStack, Outputs.VPCIdOutput ]
        VPCCidrBlock: !GetAtt [ CoreVPCStack, Outputs.VPCCidrBlockOutput ]
        MLEngineBYOAppSecurityGroupIDs: !Join [ ",", !Ref MLEngineBYOAppSecurityGroupIDs ]
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-security-groups.yml"
  MLEngineECSTaskDefinitionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        MLEngineECSTaskRoleARN: !GetAtt [ MLEngineIAMStack, Outputs.MLEngineTaskRoleOutput ]
        MLEngineECSTaskExecutionRoleARN: !GetAtt [ MLEngineIAMStack, Outputs.MLEngineTaskExecutionRoleOutput ]
        MLEngineVersion: !Ref MLEngineVersion
        MLEngineContainerImageLocation: !Ref MLEngineContainerImageLocation
        ContainerRepositoryCredentialRequired: !If [ ContainerRepositoryCredentialRequired, 'true', 'false' ]
        ContainerRepositoryCredentialsSecretARN: !GetAtt [ CoreSecretsStack, Outputs.ContainerRepositoryCredentialsSecretOutput ]
        MLEngineArthurApiHost: !Ref ArthurApiHost
        MLEngineClientCredentialsSecretARN: !GetAtt [ MLEngineSecretsStack, Outputs.MLEngineClientCredentialsSecretOutput ]
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-ecs-task-definition.yml"
  MLEngineECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurECSClusterName: !GetAtt [ CoreECSStack, Outputs.ArthurECSClusterNameOutput ]
        MLEngineECSSecurityGroups: !GetAtt [ MLEngineSecurityGroupStack, Outputs.MLEngineAppSecurityGroupsOutput ]
        MLEngineECSServiceSubnetIDs: !Join [ ',', !Ref ArthurPrivateSubnets ]
        MLEngineECSTaskDefinitionARN: !GetAtt [ MLEngineECSTaskDefinitionStack, Outputs.MLEngineECSTaskDefinitionOutput ]
        MLEngineECSScaleCPUTargetValue: !Ref MLEngineECSScaleCPUTargetValue
        MLEngineECSScaleMemoryTargetValue: !Ref MLEngineECSScaleMemoryTargetValue
        MLEngineECSScaleInCooldownInSecs: !Ref MLEngineECSScaleInCooldownInSecs
        MLEngineECSScaleOutCooldownInSecs: !Ref MLEngineECSScaleOutCooldownInSecs
        MLEngineECSAutoscalingMaxCapacity: !Ref MLEngineECSAutoscalingMaxCapacity
        MLEngineECSAutoscalingMinCapacity: !Ref MLEngineECSAutoscalingMinCapacity
        MLEngineECSServiceTaskDesiredCount: !Ref MLEngineECSServiceTaskDesiredCount
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-ecs.yml"
  MLEngineCloudwatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ArthurECSClusterName: !GetAtt [ CoreECSStack, Outputs.ArthurECSClusterNameOutput ]
        MLEngineECSServiceName: !GetAtt [ MLEngineECSStack, Outputs.MLEngineECSServiceNameOutput ]
        MLEngineECSCPUAlarmThreshold: !Ref MLEngineECSCPUAlarmThreshold
        MLEngineECSMemoryAlarmThreshold: !Ref MLEngineECSMemoryAlarmThreshold
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-cloudwatch-alarms.yml"
  MLEngineCloudwatchDashboardStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ArthurResourceNamespace: !Ref ArthurResourceNamespace
        ArthurResourceNameSuffix: !Ref ArthurResourceNameSuffix
        ArthurECSClusterName: !GetAtt [ CoreECSStack, Outputs.ArthurECSClusterNameOutput ]
        MLEngineECSServiceName: !GetAtt [ MLEngineECSStack, Outputs.MLEngineECSServiceNameOutput ]
      TemplateURL: "https://arthur-cft.s3.us-east-2.amazonaws.com/arthur-engine/templates/REPLACE_ME_GENAI_ENGINE_VERSION/arthur-ml-engine-cloudwatch-dashboard.yml"
