# Chart.yaml
apiVersion: v2
name: arthur-engine
version: 0.0.4-lts
dependencies:
- name: arthur-genai-engine
  version: 2.1.543
  repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
- name: arthur-ml-engine
  version: 2.1.543
  repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
