# Chart.yaml
apiVersion: v2
name: arthur-engine
version: 0.0.8-lts
dependencies:
- name: arthur-genai-engine
  version: 0.0.8-lts
  repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
- name: arthur-ml-engine
  version: 0.0.8-lts
  repository: oci://ghcr.io/arthur-ai/arthur-engine/charts
