name: GenAI Engine CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-linter:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    env:
      SKIP: pytest-check,changelog-check
      GIT_DEPTH: 100
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Run pre-commit
        run: |
          poetry -C genai-engine run pre-commit install
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "$CHANGED_FILES" | xargs poetry -C genai-engine run pre-commit run --color always --verbose --files

  run-changelog-cop:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Install oasdiff
        run: |
          curl -L -o "oasdiff.deb" https://github.com/Tufin/oasdiff/releases/download/v1.10.23/oasdiff_1.10.23_linux_amd64.deb
          dpkg -i oasdiff.deb
      - name: Generate changelog
        run: |
          export PYTHONPATH=src
          poetry -C genai-engine run generate_changelog
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: changelog-artifacts
          path: |
            new.openapi.json
            staging.openapi.json
            src/api_changelog.md


  run-unit-tests:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Run unit tests
        run: |
          poetry -C genai-engine run pytest --cov --cov=genai-engine/src --cov-report term --junitxml=report.xml -m "unit_tests" | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: genai-engine/report.xml
          title: Coverage Report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            genai-engine/report.xml
            pytest-coverage.txt
