name: GenAI Engine CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-dev'
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-linter:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-common version to') ||
       !contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    env:
      SKIP: pytest-check,changelog-check
      GIT_DEPTH: 100
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Run pre-commit
        run: |
          poetry -C genai-engine run pre-commit install
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "$CHANGED_FILES" | xargs poetry -C genai-engine run pre-commit run --color always --verbose --files

  run-changelog-cop:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-common version to') ||
       !contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Install oasdiff
        run: |
          curl -L -o "oasdiff.deb" https://github.com/Tufin/oasdiff/releases/download/v1.10.23/oasdiff_1.10.23_linux_amd64.deb
          dpkg -i oasdiff.deb
      - name: Generate changelog
        run: |
          export PYTHONPATH=src
          poetry -C genai-engine run generate_changelog
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: changelog-artifacts
          path: |
            new.openapi.json
            staging.openapi.json
            src/api_changelog.md


  run-unit-tests:
    if: |
      (!contains(github.event.head_commit.message, 'Increment arthur-common version to') ||
       !contains(github.event.head_commit.message, 'Increment arthur-engine version to')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Run unit tests
        run: |
          poetry -C genai-engine run pytest --cov --cov=genai-engine/src --cov-report term --junitxml=report.xml -m "unit_tests" | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: genai-engine/report.xml
          title: Coverage Report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            genai-engine/report.xml
            pytest-coverage.txt



  push-tag:
    if: |
      contains(github.event.head_commit.message, 'Increment arthur-engine version to') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - name: Push tag
        run: |
          VERSION=$(cat genai-engine/version)
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            VERSION="${VERSION}-dev"
          fi
          git tag -a "$VERSION" -m "Create tag $VERSION"
          git push origin "$VERSION"

  build-docker-images:
    needs: push-tag
    environment: shared-protected-branch-secrets
    if: |
      contains(github.event.head_commit.message, 'Increment arthur-engine version to') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        torch_device: [cpu, gpu]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - name: Set version
        run: |
          VERSION=$(cat genai-engine/version)
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            VERSION="${VERSION}-dev"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: "{{defaultContext}}:genai-engine"
          file: dockerfile
          build-args: |
            TORCH_DEVICE=${{ matrix.torch_device }}
            ENABLE_TELEMETRY=${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          tags: |
            arthurplatform/genai-engine-${{ matrix.torch_device }}:${{ env.VERSION }}
            ${{ github.ref == 'refs/heads/main' && format('arthurplatform/genai-engine-{0}:latest', matrix.torch_device) || '' }}
          push: true
          platforms: linux/amd64

  push-cf-template:
    needs: [push-tag, build-docker-images]
    environment: shared-protected-branch-secrets
    if: |
      contains(github.event.head_commit.message, 'Increment arthur-engine version to') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-2
      BUCKET_NAME: arthur-cft
      TEMPLATES_DIRECTORY: arthur-engine
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
      - name: Set version
        run: |
          VERSION=$(cat genai-engine/version)
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            VERSION="${VERSION}-dev"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@f503a1870408dcf2c35d5c2b8a68e69211042c7d
        with:
          role-to-assume: ${{ secrets.AWS_S3_ROLE_ARN }}
          role-session-name: ${{ secrets.AWS_S3_ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: push cf template
        run: |
          echo "Pushing Cloudformation template for ${{ env.VERSION }}"
          sed -i "s/REPLACE_ME_GENAI_ENGINE_VERSION/${{ env.VERSION }}/g" deployment/cloudformation/root-arthur-engine-cpu.yml
          sed -i "s/REPLACE_ME_GENAI_ENGINE_VERSION/${{ env.VERSION }}/g" deployment/cloudformation/root-arthur-engine-gpu.yml
          sed -i "s/REPLACE_ME_GENAI_ENGINE_VERSION/${{ env.VERSION }}/g" deployment/cloudformation/root-arthur-genai-engine-cpu.yml
          sed -i "s/REPLACE_ME_GENAI_ENGINE_VERSION/${{ env.VERSION }}/g" deployment/cloudformation/root-arthur-genai-engine-gpu.yml
          aws s3 sync ./deployment/cloudformation/ s3://${{ env.BUCKET_NAME }}/${{ env.TEMPLATES_DIRECTORY }}/templates/${{ env.VERSION }} --acl public-read

  push-helm-chart-to-github-dev:
    needs: [push-tag, build-docker-images]
    environment: shared-protected-branch-secrets
    if: |
      contains(github.event.head_commit.message, 'Increment arthur-engine version to') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-helm
      - name: Set version
        run: |
          VERSION=$(cat genai-engine/version)
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            VERSION="${VERSION}-dev"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Package and Push Helm chart
        env:
          CHART_PATH_GENAI_ENGINE: "deployment/helm/genai-engine"
          CHART_PATH_ML_ENGINE: "deployment/helm/ml-engine"
          CHART_NAMESPACE: ${{ github.ref == 'refs/heads/main' && 'charts' || 'charts-dev' }}
        run: |
          helm package ${CHART_PATH_GENAI_ENGINE} --version ${{ env.VERSION }} --app-version ${{ env.VERSION }}
          helm push arthur-genai-engine-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository }}/${{ env.CHART_NAMESPACE }}
          helm package ${CHART_PATH_ML_ENGINE} --version ${{ env.VERSION }} --app-version ${{ env.VERSION }}
          helm push arthur-ml-engine-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository }}/${{ env.CHART_NAMESPACE }}
