name: ML Engine Test

on:
  push:
    branches:
      - main
      - dev
      - fix_ml_build
  pull_request:
    branches:
      - main
      - dev
      - fix_ml_build

jobs:
  build-ml-engine-docker-images:
    environment: shared-protected-branch-secrets
    if: |
      (github.ref == 'refs/heads/fix_ml_build')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/set-version
      - name: Generate GenAI Client
        run: |
          pip install openapi-generator-cli[jdk4py]
          openapi-generator-cli generate -g python \
            -i ./genai-engine/staging.openapi.json \
            -o ./ml-engine/src/genai_client \
            --skip-validate-spec --package-name genai_client
          sed -i 's/license = "NoLicense"/license = "Unlicense"/g' ./ml-engine/src/genai_client/pyproject.toml
      - name: Debug
        run: |
          echo "Checking if staging.openapi.json exists:"
          ls -la ./genai-engine/staging.openapi.json
          echo "Checking ml-engine/src directory:"
          ls -la ./ml-engine/src/
          echo "Checking if genai_client was generated:"
          ls -la ./ml-engine/src/genai_client || echo "genai_client directory not found"
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3.10.0
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3.4.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Build and push docker image
      #   uses: docker/build-push-action@v6.15.0
      #   with:
      #     context: "{{defaultContext}}:ml-engine"
      #     file: Dockerfile
      #     tags: |
      #       arthurplatform/ml-engine:${{ env.VERSION }}
      #       ${{ github.ref == 'refs/heads/main' && format('arthurplatform/ml-engine:latest') || '' }}
      #     push: true
      #     platforms: linux/amd64
