name: Reusable Deployments

on:
  workflow_call:
    inputs:
      aws_account:
        required: true
        type: string
        default: 'sts-arthur-test'
      version:
        required: true
        type: string
        default: 'x.y.z-dev'
      selection:
        required: true
        type: string

jobs:
  deploy-genai-engine-cpu:
    if: inputs.selection == 'genai-engine-cpu'
    runs-on: ubuntu-latest
    environment: shared-protected-branch-secrets
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Settings
        run: |
          echo "AWS Account: ${{ inputs.aws_account }}"
          echo "Version: ${{ inputs.version }}"
          echo "Selection: ${{ inputs.selection }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@f503a1870408dcf2c35d5c2b8a68e69211042c7d
        with:
          role-to-assume: arn:aws:iam::587035402297:role/github-actions-role-1
          role-session-name: test-s3-access-from-github
          aws-region: us-east-2
      - name: Test AWS Access
        run: |
          echo "test" > test.txt
          aws s3 cp test.txt s3://test-bucket-2874739283/test.txt

  # deploy-ml-engine:
  #   if: inputs.selection == 'all'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Settings
  #       run: |
  #         echo "AWS Account: ${{ inputs.aws_account }}"
  #         echo "Version: ${{ inputs.version }}"
  #         echo "Selection: ${{ inputs.selection }}"

  # deploy-arthur-engine:
  #   if: inputs.selection == 'all'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Settings
  #       run: |
  #         echo "AWS Account: ${{ inputs.aws_account }}"
  #         echo "Version: ${{ inputs.version }}"
  #         echo "Selection: ${{ inputs.selection }}"
