name: Version Management

on:
  pull_request:
    branches:
      - UP-2590-publish-common-pypi
    paths:
      - '.github/workflows/**/*'
      - 'genai-engine/alembic/**/*'
      - 'genai-engine/src/**/*'
      - 'genai-engine/tests/**/*'
      - 'genai-engine/.env'
      - 'genai-engine/dockerfile'
      - 'genai-engine/pyproject.toml'
      - 'genai-engine/requirements-gpu.txt'
      - 'deployment/cloudformation/**/*'
      - 'deployment/helm/**/*'
      - 'arthur-common/src/**/*'
      - 'arthur-common/tests/**/*'
      - 'arthur-common/pyproject.toml'

jobs:
  bump-and-tag-version:
    environment: shared-protected-branch-secrets
#    if: |
#      github.event_name != 'pull_request' &&
#      (github.ref == 'refs/heads/dev') &&
#      !contains(github.event.head_commit.message, 'Increment version to') &&
#      (
#        github.event_name == 'push' ||
#        (github.event_name == 'workflow_dispatch' && github.event.inputs.intent == 'bump_version')
#      )
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite-actions/setup-git
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Bump Version
        env:
          GENAI_ENGINE_HELM_CHART_YAML_PATH: "../deployment/helm/genai-engine/Chart.yaml"
          GENAI_ENGINE_HELM_VALUES_YAML_PATH: "../deployment/helm/genai-engine/values.yaml.template"
          ARTHUR_ENGINE_HELM_CPU_START_SCRIPT_PATH: "../deployment/helm/arthur-engine/start.sh.template.cpu"
          ARTHUR_ENGINE_HELM_GPU_START_SCRIPT_PATH: "../deployment/helm/arthur-engine/start.sh.template.gpu"
          ARTHUR_ENGINE_CFT_CPU_HTML_PATH: "../deployment/cloudformation/start-cpu-stack.html"
          ARTHUR_ENGINE_CFT_GPU_HTML_PATH: "../deployment/cloudformation/start-gpu-stack.html"
          ARTHUR_ENGINE_CHART_YAML_PATH: "../deployment/helm/arthur-engine/Chart.yaml"
          ARTHUR_ENGINE_VALUES_YAML_PATH: "../deployment/helm/arthur-engine/values.yaml.template"
        run: |
          set -e

          # Vars to externalize if needed
          export SUFFIX="-dev"
          export BUMP_COMMAND="patch"
          export BRANCH_NAME="version-bump/$(date +%Y%m%d-%H%M%S)"

          # Update files in the arthur-common directory
          cd arthur-common

          # Set version vars with no suffix
          export CURRENT_VERSION=$(poetry version -s)
          export NEW_VERSION="$(poetry version "${BUMP_COMMAND}" -s)"

          # Validate version variables are set
          if [ -z "$CURRENT_VERSION" ] || [ -z "$NEW_VERSION" ]; then
            echo "Error: Version variables not set. CURRENT_VERSION='$CURRENT_VERSION', NEW_VERSION='$NEW_VERSION'"
            exit 1
          fi

          # Update files in the genai-engine directory
          cd ../genai-engine
          export NEW_GENAI_VERSION="$(poetry version "${BUMP_COMMAND}" -s)"

          # validate new genai version is the same as new arthur common version
          if [ -z "$NEW_GENAI_VERSION" ] || [ "$NEW_VERSION" != "$NEW_GENAI_VERSION" ]; then
            echo "Error: New Gen AI version and new Arthur Common versions are not the same. NEW_GENAI_VERSION='$NEW_GENAI_VERSION', NEW_ARTHUR_COMMON_VERSION='$NEW_VERSION'"
            exit 1
          fi

          # Create and checkout new branch
          git checkout -b "$BRANCH_NAME"

          # Rest of the version update logic
          export GIT_TAG=$NEW_VERSION$SUFFIX
          echo "New version will be ${NEW_VERSION}[${SUFFIX}]"
          echo $NEW_VERSION > version
          sed -i "s|genaiEngineVersion:.*|genaiEngineVersion: '$NEW_VERSION'|" "$GENAI_ENGINE_HELM_VALUES_YAML_PATH"
          sed -i "s|version:.*|version: $NEW_VERSION|" "$GENAI_ENGINE_HELM_CHART_YAML_PATH"
          sed -i "s|appVersion:.*|appVersion: $NEW_VERSION|" "$GENAI_ENGINE_HELM_CHART_YAML_PATH"

          sed -i "s/ARTHUR_ENGINE_VERSION=.*/ARTHUR_ENGINE_VERSION=$NEW_VERSION/" "$ARTHUR_ENGINE_HELM_CPU_START_SCRIPT_PATH"
          sed -i "s/ARTHUR_ENGINE_VERSION=.*/ARTHUR_ENGINE_VERSION=$NEW_VERSION/" "$ARTHUR_ENGINE_HELM_GPU_START_SCRIPT_PATH"
          sed -i "s|arthur-engine/templates/[0-9]\+\.[0-9]\+\.[0-9]\+/root-arthur-engine|arthur-engine/templates/$NEW_VERSION/root-arthur-engine|" "$ARTHUR_ENGINE_CFT_GPU_HTML_PATH"
          sed -i "s|arthur-engine/templates/[0-9]\+\.[0-9]\+\.[0-9]\+/root-arthur-engine|arthur-engine/templates/$NEW_VERSION/root-arthur-engine|" "$ARTHUR_ENGINE_CFT_CPU_HTML_PATH"
          sed -i "s|genaiEngineVersion:.*|genaiEngineVersion: $NEW_VERSION|" "$ARTHUR_ENGINE_VALUES_YAML_PATH"
          sed -i "s|version:.*|version: $NEW_VERSION|" "$ARTHUR_ENGINE_CHART_YAML_PATH"

          # Add and commit changes
          git add version pyproject.toml $GENAI_ENGINE_HELM_CHART_YAML_PATH $GENAI_ENGINE_HELM_VALUES_YAML_PATH $ARTHUR_ENGINE_HELM_CPU_START_SCRIPT_PATH $ARTHUR_ENGINE_HELM_GPU_START_SCRIPT_PATH $ARTHUR_ENGINE_CFT_GPU_HTML_PATH $ARTHUR_ENGINE_CFT_CPU_HTML_PATH $ARTHUR_ENGINE_CHART_YAML_PATH $ARTHUR_ENGINE_VALUES_YAML_PATH
          git status
          git diff --cached
#          git commit --no-verify -m "Increment version to ${NEW_VERSION}"
#
#          # Push the new branch with the commit
#          git push -u origin "$BRANCH_NAME"
#
#      - name: Create Pull Request
#        env:
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          gh pr create \
#            --title "Increment version to $(cat genai-engine/version)" \
#            --body "Increment version to $(cat genai-engine/version)" \
#            --base ${GITHUB_REF#refs/heads/} \
#            --head "$BRANCH_NAME"
