name: Version Management

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '.github/workflows/**/*'
      - 'genai-engine/alembic/**/*'
      - 'genai-engine/cloudformation/**/*'
      - 'genai-engine/genai_engine/**/*'
      - 'genai-engine/helm/**/*'
      - 'genai-engine/shield/**/*'
      - 'genai-engine/tests/**/*'
      - 'genai-engine/.env'
      - 'genai-engine/dockerfile'
      - 'genai-engine/pyproject.toml'
      - 'genai-engine/requirements-gpu.txt'
  workflow_dispatch:
    inputs:
      intent:
        description: 'Trigger version bump'
        required: true
        default: 'bump_version'
        type: string

jobs:
  bump-and-tag-version:
    environment: shared-protected-branch-secrets
    if: |
      github.event_name != 'pull_request' &&
      (github.ref == 'refs/heads/dev') &&
      !contains(github.event.head_commit.message, 'Increment version to') &&
      (
        github.event_name == 'push' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.intent == 'bump_version')
      )
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/composite-actions/setup-git
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          working-directory: genai-engine
      - name: Bump Version
        env:
          HELM_CHART_YAML_PATH: "helm/Chart.yaml"
          HELM_VALUES_YAML_PATH: "helm/values.yaml.template"
          HELM_CPU_START_SCRIPT_PATH: "helm/start.sh.template.cpu"
          HELM_GPU_START_SCRIPT_PATH: "helm/start.sh.template.gpu"
          CFT_CPU_HTML_PATH: "cloudformation/start-cpu.html"
          CFT_GPU_HTML_PATH: "cloudformation/start-gpu.html"
        run: |
          set -e

          # Update files in the genai-engine directory
          cd genai-engine

          # Vars to externalize if needed
          export SUFFIX="-dev"
          export BUMP_COMMAND="patch"
          export BRANCH_NAME="version-bump/$(date +%Y%m%d-%H%M%S)"

          # Set version vars with no suffix
          export CURRENT_VERSION=$(poetry version -s)
          export NEW_VERSION="$(poetry version "${BUMP_COMMAND}" -s)"

          # Validate version variables are set
          if [ -z "$CURRENT_VERSION" ] || [ -z "$NEW_VERSION" ]; then
            echo "Error: Version variables not set. CURRENT_VERSION='$CURRENT_VERSION', NEW_VERSION='$NEW_VERSION'"
            exit 1
          fi

          # Create and checkout new branch
          git checkout -b "$BRANCH_NAME"

          # Rest of the version update logic
          export GIT_TAG=$NEW_VERSION$SUFFIX
          echo "New version will be ${NEW_VERSION}[${SUFFIX}]"
          echo $NEW_VERSION > version
          sed -i "s|genaiEngineVersion:.*|genaiEngineVersion: '$NEW_VERSION'|" "$HELM_VALUES_YAML_PATH"
          sed -i "s|version:.*|version: $NEW_VERSION|" "$HELM_CHART_YAML_PATH"
          sed -i "s|appVersion:.*|appVersion: $NEW_VERSION|" "$HELM_CHART_YAML_PATH"
          sed -i "s/GENAI_ENGINE_VERSION=.*/GENAI_ENGINE_VERSION=$NEW_VERSION/" "$HELM_CPU_START_SCRIPT_PATH"
          sed -i "s/GENAI_ENGINE_VERSION=.*/GENAI_ENGINE_VERSION=$NEW_VERSION/" "$HELM_GPU_START_SCRIPT_PATH"
          sed -i "s|/templates/[0-9]\+\.[0-9]\+\.[0-9]\+/|/templates/$NEW_VERSION/|" "$CFT_GPU_HTML_PATH"
          sed -i "s|/templates/[0-9]\+\.[0-9]\+\.[0-9]\+/|/templates/$NEW_VERSION/|" "$CFT_CPU_HTML_PATH"

          # Add and commit changes
          git add version pyproject.toml $HELM_CHART_YAML_PATH $HELM_VALUES_YAML_PATH $HELM_CPU_START_SCRIPT_PATH $HELM_GPU_START_SCRIPT_PATH
          git status
          git diff --cached
          git commit --no-verify -m "Increment version to ${NEW_VERSION}"

          # Push the new branch with the commit
          git push -u origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "Increment version to $(cat genai-engine/version)" \
            --body "Increment version to $(cat genai-engine/version)" \
            --base ${GITHUB_REF#refs/heads/} \
            --head "$BRANCH_NAME"
